import datetime
from pathlib import *
from lineapy.data.types import *
from lineapy.utils.utils import get_new_id

source_1 = SourceCode(
    code="""bs = [1,2]
if len(bs) > 4:
    pass
else:
    bs.append(3)
""",
    location=PosixPath("[source file path]"),
)
call_1 = CallNode(
    source_location=SourceLocation(
        lineno=1,
        col_offset=5,
        end_lineno=1,
        end_col_offset=10,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_list",
    ).id,
    positional_args=[
        LiteralNode(
            source_location=SourceLocation(
                lineno=1,
                col_offset=6,
                end_lineno=1,
                end_col_offset=7,
                source_code=source_1.id,
            ),
            value=1,
        ).id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=1,
                col_offset=8,
                end_lineno=1,
                end_col_offset=9,
                source_code=source_1.id,
            ),
            value=2,
        ).id,
    ],
)
if_1 = IfNode(
    source_location=SourceLocation(
        lineno=2,
        col_offset=3,
        end_lineno=2,
        end_col_offset=14,
        source_code=source_1.id,
    ),
    companion_id=else_1.id,
    test_id=CallNode(
        source_location=SourceLocation(
            lineno=2,
            col_offset=3,
            end_lineno=2,
            end_col_offset=14,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="gt",
        ).id,
        positional_args=[
            CallNode(
                source_location=SourceLocation(
                    lineno=2,
                    col_offset=3,
                    end_lineno=2,
                    end_col_offset=10,
                    source_code=source_1.id,
                ),
                function_id=LookupNode(
                    source_location=SourceLocation(
                        lineno=2,
                        col_offset=3,
                        end_lineno=2,
                        end_col_offset=6,
                        source_code=source_1.id,
                    ),
                    name="len",
                ).id,
                positional_args=[call_1.id],
            ).id,
            LiteralNode(
                source_location=SourceLocation(
                    lineno=2,
                    col_offset=13,
                    end_lineno=2,
                    end_col_offset=14,
                    source_code=source_1.id,
                ),
                value=4,
            ).id,
        ],
    ).id,
)
unexec_1 = UnexecNode(
    source_location=SourceLocation(
        lineno=3,
        col_offset=4,
        end_lineno=3,
        end_col_offset=8,
        source_code=source_1.id,
    ),
    control_dependency=if_1.id,
)
call_4 = CallNode(
    source_location=SourceLocation(
        lineno=3,
        col_offset=4,
        end_lineno=3,
        end_col_offset=8,
        source_code=source_1.id,
    ),
    control_dependency=unexec_1.id,
    function_id=LookupNode(
        control_dependency=unexec_1.id,
        name="l_exec_statement",
    ).id,
    positional_args=[
        LiteralNode(
            source_location=SourceLocation(
                lineno=3,
                col_offset=4,
                end_lineno=3,
                end_col_offset=8,
                source_code=source_1.id,
            ),
            control_dependency=unexec_1.id,
            value="pass",
        ).id
    ],
)
else_1 = ElseNode(
    source_location=SourceLocation(
        lineno=4,
        col_offset=0,
        end_lineno=4,
        end_col_offset=4,
        source_code=source_1.id,
    ),
    companion_id=if_1.id,
)
mutate_1 = MutateNode(
    control_dependency=else_1.id,
    source_id=call_1.id,
    call_id=CallNode(
        source_location=SourceLocation(
            lineno=5,
            col_offset=4,
            end_lineno=5,
            end_col_offset=16,
            source_code=source_1.id,
        ),
        control_dependency=else_1.id,
        function_id=CallNode(
            source_location=SourceLocation(
                lineno=5,
                col_offset=4,
                end_lineno=5,
                end_col_offset=13,
                source_code=source_1.id,
            ),
            control_dependency=else_1.id,
            function_id=LookupNode(
                control_dependency=else_1.id,
                name="getattr",
            ).id,
            positional_args=[
                call_1.id,
                LiteralNode(
                    control_dependency=else_1.id,
                    value="append",
                ).id,
            ],
        ).id,
        positional_args=[
            LiteralNode(
                source_location=SourceLocation(
                    lineno=5,
                    col_offset=14,
                    end_lineno=5,
                    end_col_offset=15,
                    source_code=source_1.id,
                ),
                control_dependency=else_1.id,
                value=3,
            ).id
        ],
    ).id,
)
