site_name: LineaPy

theme:
  name: material
  custom_dir: overrides
  logo: images/icon-lineapy-white.png
  favicon: images/lineapy-square-light.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Concepts:
    - Artifact: concepts/artifact.md
    - Artifact Store: concepts/artifact-store.md
    - Pipeline: concepts/pipeline.md
  - Tutorials:
    - tutorials/00_lineapy_quickstart.ipynb
    - tutorials/01_using_artifacts.ipynb
    - tutorials/02_pipeline_building.ipynb
  - Guides:
    - Installation and Setup: guides/setup.md

repo_name: LineaLabs/lineapy
repo_url: https://github.com/LineaLabs/lineapy

plugins:
  - search
  - mkdocs-jupyter
