import logging
from enum import Enum
from typing import Any, Dict, List

from pydantic import BaseModel
from typing_extensions import TypedDict

from lineapy.plugins.base_pipeline_writer import BasePipelineWriter
from lineapy.plugins.task import DagTaskBreakdown
from lineapy.plugins.taskgen import get_task_graph
from lineapy.plugins.utils import load_plugin_template
from lineapy.utils.logging_config import configure_logging

logger = logging.getLogger(__name__)
configure_logging()


class Stage(BaseModel):
    name: str
    deps: List[str]
    outs: List[str]
    call_block: str
    user_input_variables: Dict[str, Any]


class DVCDagFlavor(Enum):
    SingleStageAllSessions = 1
    StagePerArtifact = 2
    # TODO: StagePerSession


DVCDagConfig = TypedDict(
    "DVCDagConfig",
    {
        "dag_flavor": str,  # Not native to DVC config
    },
    total=False,
)


class DVCPipelineWriter(BasePipelineWriter):
    """
    Class for pipeline file writer. Corresponds to "DVC" framework.
    """

    @property
    def docker_template_name(self) -> str:
        return "dvc/dvc_dockerfile.jinja"

    def _write_dag(self) -> None:
        dag_flavor = self.dag_config.get("dag_flavor", "StagePerArtifact")

        # Check if the given DAG flavor is a supported/valid one
        if dag_flavor not in DVCDagFlavor.__members__:
            raise ValueError(f'"{dag_flavor}" is an invalid dvc dag flavor.')

        # Construct DAG text for the given flavor
        if DVCDagFlavor[dag_flavor] == DVCDagFlavor.SingleStageAllSessions:
            dvc_yaml_code = self._write_operator_run_all_sessions()

        if DVCDagFlavor[dag_flavor] == DVCDagFlavor.StagePerArtifact:
            dvc_yaml_code = self._write_operator_run_per_artifact()

        # Write out file
        dvc_dag_file = self.output_dir / "dvc.yaml"
        dvc_dag_file.write_text(dvc_yaml_code)
        logger.info(f"Generated DAG file: {dvc_dag_file}")

    def _write_operator_run_all_sessions(self) -> str:
        """
        This hidden method implements DVC DAG code generation corresponding
        to the `SingleStageAllSessions` flavor. This DAG only has one stage and
        calls `run_all_sessions` generated by the module file.
        """

        DAG_TEMPLATE = load_plugin_template(
            "dvc/dvc_dag_SingleStageAllSessions.jinja"
        )

        full_code = DAG_TEMPLATE.render(
            MODULE_COMMAND=f"python {self.pipeline_name}_module.py",
        )

        return full_code

    def _write_operator_run_per_artifact(self) -> str:
        """
        This hidden method implements DVC DAG code generation corresponding
        to the `StagePerArtifact` flavor.
        """

        DAG_TEMPLATE = load_plugin_template(
            "dvc/dvc_dag_StagePerArtifact.jinja"
        )

        task_defs, _ = get_task_graph(
            self.artifact_collection,
            pipeline_name=self.pipeline_name,
            task_breakdown=DagTaskBreakdown.TaskPerArtifact,
        )

        # Get DAG parameters for an ARGO pipeline
        input_parameters_dict: Dict[str, Any] = {}
        for parameter_name, input_spec in super().get_pipeline_args().items():
            input_parameters_dict[parameter_name] = input_spec.value

        stages = [
            Stage(
                name=key,
                deps=value.loaded_input_variables,
                outs=value.return_vars,
                call_block=value.call_block,
                user_input_variables={
                    key: input_parameters_dict[key]
                    for key in value.user_input_variables
                },
            ).dict()
            for key, value in task_defs.items()
        ]

        full_code = DAG_TEMPLATE.render(
            MODULE_NAME=f"{self.pipeline_name}_module", STAGES=stages
        )

        self._write_params(stages)

        for stage in stages:
            self._write_python_operator_per_run_artifact(stage)

        return full_code

    def _write_params(self, stages: List[dict]):
        PARAMS_TEMPLATE = load_plugin_template("dvc_dag_params.jinja")

        params_code = PARAMS_TEMPLATE.render(STAGES=stages)
        filename = "params.yaml"
        params_file = self.output_dir / filename
        params_file.write_text(params_code)
        logger.info(f"Generated DAG file: {params_file}")

    def _write_python_operator_per_run_artifact(self, stage: dict):
        """
        This hidden method generates the python cmd files for each DVC stage.
        """
        TASK_TEMPLATE = load_plugin_template(
            "dvc/dvc_dag_PythonOperator.jinja"
        )

        python_operator_code = TASK_TEMPLATE.render(
            MODULE_NAME=f"{self.pipeline_name}_module", STAGE=stage
        )
        filename = f"task_{stage['name']}.py"
        python_operator_file = self.output_dir / filename
        python_operator_file.write_text(python_operator_code)
        logger.info(f"Generated DAG file: {python_operator_file}")
