import datetime
from pathlib import *
from lineapy.data.types import *
from lineapy.utils import get_new_id

source_1 = SourceCode(
    code="""x = 1>2
y = 1<2
z = x and y
q = (1>2 or 1<2)
""",
    location=PosixPath("[source file path]"),
)
call_3 = CallNode(
    source_location=SourceLocation(
        lineno=3,
        col_offset=4,
        end_lineno=3,
        end_col_offset=11,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="and_",
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=1,
                col_offset=4,
                end_lineno=1,
                end_col_offset=7,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="gt",
            ).id,
            positional_args=[
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=1,
                        col_offset=4,
                        end_lineno=1,
                        end_col_offset=5,
                        source_code=source_1.id,
                    ),
                    value=1,
                ).id,
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=1,
                        col_offset=6,
                        end_lineno=1,
                        end_col_offset=7,
                        source_code=source_1.id,
                    ),
                    value=2,
                ).id,
            ],
        ).id,
        CallNode(
            source_location=SourceLocation(
                lineno=2,
                col_offset=4,
                end_lineno=2,
                end_col_offset=7,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="lt",
            ).id,
            positional_args=[
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=2,
                        col_offset=4,
                        end_lineno=2,
                        end_col_offset=5,
                        source_code=source_1.id,
                    ),
                    value=1,
                ).id,
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=2,
                        col_offset=6,
                        end_lineno=2,
                        end_col_offset=7,
                        source_code=source_1.id,
                    ),
                    value=2,
                ).id,
            ],
        ).id,
    ],
)
call_6 = CallNode(
    source_location=SourceLocation(
        lineno=4,
        col_offset=5,
        end_lineno=4,
        end_col_offset=15,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="or_",
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=4,
                col_offset=5,
                end_lineno=4,
                end_col_offset=8,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="gt",
            ).id,
            positional_args=[
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=4,
                        col_offset=5,
                        end_lineno=4,
                        end_col_offset=6,
                        source_code=source_1.id,
                    ),
                    value=1,
                ).id,
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=4,
                        col_offset=7,
                        end_lineno=4,
                        end_col_offset=8,
                        source_code=source_1.id,
                    ),
                    value=2,
                ).id,
            ],
        ).id,
        CallNode(
            source_location=SourceLocation(
                lineno=4,
                col_offset=12,
                end_lineno=4,
                end_col_offset=15,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="lt",
            ).id,
            positional_args=[
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=4,
                        col_offset=12,
                        end_lineno=4,
                        end_col_offset=13,
                        source_code=source_1.id,
                    ),
                    value=1,
                ).id,
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=4,
                        col_offset=14,
                        end_lineno=4,
                        end_col_offset=15,
                        source_code=source_1.id,
                    ),
                    value=2,
                ).id,
            ],
        ).id,
    ],
)
