import datetime
from lineapy.data.types import *
from lineapy.utils import get_new_id

session = SessionContext(
    id=get_new_id(),
    environment_type=SessionType.STATIC,
    creation_time=datetime.datetime(1, 1, 1, 0, 0),
    file_name="[source file path]",
    code="[0][abs(0)]",
    working_directory="dummy_linea_repo/",
    libraries=[],
)
call_3 = CallNode(
    id=get_new_id(),
    session_id=session.id,
    lineno=1,
    col_offset=0,
    end_lineno=1,
    end_col_offset=11,
    arguments=[
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            positional_order=0,
            value_node_id=CallNode(
                id=get_new_id(),
                session_id=session.id,
                lineno=1,
                col_offset=0,
                end_lineno=1,
                end_col_offset=3,
                arguments=[
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=0,
                        value_node_id=LiteralNode(
                            id=get_new_id(),
                            session_id=session.id,
                            lineno=1,
                            col_offset=1,
                            end_lineno=1,
                            end_col_offset=2,
                            value=0,
                        ).id,
                    ).id
                ],
                function_id=LookupNode(
                    id=get_new_id(),
                    session_id=session.id,
                    name="__build_list__",
                ).id,
            ).id,
        ).id,
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            positional_order=1,
            value_node_id=CallNode(
                id=get_new_id(),
                session_id=session.id,
                lineno=1,
                col_offset=4,
                end_lineno=1,
                end_col_offset=10,
                arguments=[
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=0,
                        value_node_id=LiteralNode(
                            id=get_new_id(),
                            session_id=session.id,
                            lineno=1,
                            col_offset=8,
                            end_lineno=1,
                            end_col_offset=9,
                            value=0,
                        ).id,
                    ).id
                ],
                function_id=LookupNode(
                    id=get_new_id(),
                    session_id=session.id,
                    name="abs",
                ).id,
            ).id,
        ).id,
    ],
    function_id=LookupNode(
        id=get_new_id(),
        session_id=session.id,
        name="getitem",
    ).id,
)
