import datetime
from pathlib import *
from lineapy.data.types import *
from lineapy.utils import get_new_id

session = SessionContext(
    id=get_new_id(),
    environment_type=SessionType.SCRIPT,
    creation_time=datetime.datetime(1, 1, 1, 0, 0),
    working_directory="dummy_linea_repo/",
    libraries=[],
)
source_1 = SourceCode(
    id=get_new_id(),
    code="""from math import pow as power, sqrt as root
a = power(5, 2)
b = root(a)
""",
    location=PosixPath(
        "[source file path]"
    ),
)
import_1 = ImportNode(
    id=get_new_id(),
    session_id=session.id,
    source_location=SourceLocation(
        lineno=1,
        col_offset=0,
        end_lineno=1,
        end_col_offset=43,
        source_code=source_1.id,
    ),
    library=Library(
        id=get_new_id(),
        name="math",
    ),
    attributes={"power": "pow", "root": "sqrt"},
)
variable_4 = VariableNode(
    id=get_new_id(),
    session_id=session.id,
    source_location=SourceLocation(
        lineno=3,
        col_offset=0,
        end_lineno=3,
        end_col_offset=11,
        source_code=source_1.id,
    ),
    source_node_id=CallNode(
        id=get_new_id(),
        session_id=session.id,
        source_location=SourceLocation(
            lineno=3,
            col_offset=4,
            end_lineno=3,
            end_col_offset=11,
            source_code=source_1.id,
        ),
        arguments=[
            ArgumentNode(
                id=get_new_id(),
                session_id=session.id,
                positional_order=0,
                value_node_id=VariableNode(
                    id=get_new_id(),
                    session_id=session.id,
                    source_location=SourceLocation(
                        lineno=2,
                        col_offset=0,
                        end_lineno=2,
                        end_col_offset=15,
                        source_code=source_1.id,
                    ),
                    source_node_id=CallNode(
                        id=get_new_id(),
                        session_id=session.id,
                        source_location=SourceLocation(
                            lineno=2,
                            col_offset=4,
                            end_lineno=2,
                            end_col_offset=15,
                            source_code=source_1.id,
                        ),
                        arguments=[
                            ArgumentNode(
                                id=get_new_id(),
                                session_id=session.id,
                                positional_order=0,
                                value_node_id=LiteralNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    source_location=SourceLocation(
                                        lineno=2,
                                        col_offset=10,
                                        end_lineno=2,
                                        end_col_offset=11,
                                        source_code=source_1.id,
                                    ),
                                    value=5,
                                ).id,
                            ).id,
                            ArgumentNode(
                                id=get_new_id(),
                                session_id=session.id,
                                positional_order=1,
                                value_node_id=LiteralNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    source_location=SourceLocation(
                                        lineno=2,
                                        col_offset=13,
                                        end_lineno=2,
                                        end_col_offset=14,
                                        source_code=source_1.id,
                                    ),
                                    value=2,
                                ).id,
                            ).id,
                        ],
                        function_id=VariableNode(
                            id=get_new_id(),
                            session_id=session.id,
                            source_node_id=CallNode(
                                id=get_new_id(),
                                session_id=session.id,
                                arguments=[
                                    ArgumentNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        positional_order=0,
                                        value_node_id=import_1.id,
                                    ).id,
                                    ArgumentNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        positional_order=1,
                                        value_node_id=LiteralNode(
                                            id=get_new_id(),
                                            session_id=session.id,
                                            value="pow",
                                        ).id,
                                    ).id,
                                ],
                                function_id=LookupNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    name="getattr",
                                ).id,
                            ).id,
                            assigned_variable_name="power",
                        ).id,
                    ).id,
                    assigned_variable_name="a",
                ).id,
            ).id
        ],
        function_id=VariableNode(
            id=get_new_id(),
            session_id=session.id,
            source_node_id=CallNode(
                id=get_new_id(),
                session_id=session.id,
                arguments=[
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=0,
                        value_node_id=import_1.id,
                    ).id,
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=1,
                        value_node_id=LiteralNode(
                            id=get_new_id(),
                            session_id=session.id,
                            value="sqrt",
                        ).id,
                    ).id,
                ],
                function_id=LookupNode(
                    id=get_new_id(),
                    session_id=session.id,
                    name="getattr",
                ).id,
            ).id,
            assigned_variable_name="root",
        ).id,
    ).id,
    assigned_variable_name="b",
)
