import datetime
from pathlib import *
from lineapy.data.types import *
from lineapy.utils import get_new_id

source_1 = SourceCode(
    code="""import lineapy
x = {}
y = {}
z = {}
x[\'y\'] = y
y[\'z\'] = z
z[\'a\'] = 1

lineapy.linea_publish(x, \'x\')
lineapy.linea_publish(y, \'y\')
lineapy.linea_publish(z, \'z\')
""",
    location=PosixPath("[source file path]"),
)
call_1 = CallNode(
    source_location=SourceLocation(
        lineno=2,
        col_offset=4,
        end_lineno=2,
        end_col_offset=6,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_dict",
    ).id,
)
call_2 = CallNode(
    source_location=SourceLocation(
        lineno=3,
        col_offset=4,
        end_lineno=3,
        end_col_offset=6,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_dict",
    ).id,
)
call_3 = CallNode(
    source_location=SourceLocation(
        lineno=4,
        col_offset=4,
        end_lineno=4,
        end_col_offset=6,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_dict",
    ).id,
)
call_4 = CallNode(
    source_location=SourceLocation(
        lineno=5,
        col_offset=0,
        end_lineno=5,
        end_col_offset=10,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="setitem",
    ).id,
    positional_args=[
        call_1.id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=5,
                col_offset=2,
                end_lineno=5,
                end_col_offset=5,
                source_code=source_1.id,
            ),
            value="y",
        ).id,
        call_2.id,
    ],
)
call_5 = CallNode(
    source_location=SourceLocation(
        lineno=6,
        col_offset=0,
        end_lineno=6,
        end_col_offset=10,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="setitem",
    ).id,
    positional_args=[
        call_2.id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=6,
                col_offset=2,
                end_lineno=6,
                end_col_offset=5,
                source_code=source_1.id,
            ),
            value="z",
        ).id,
        call_3.id,
    ],
)
call_6 = CallNode(
    source_location=SourceLocation(
        lineno=7,
        col_offset=0,
        end_lineno=7,
        end_col_offset=10,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="setitem",
    ).id,
    positional_args=[
        call_3.id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=7,
                col_offset=2,
                end_lineno=7,
                end_col_offset=5,
                source_code=source_1.id,
            ),
            value="a",
        ).id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=7,
                col_offset=9,
                end_lineno=7,
                end_col_offset=10,
                source_code=source_1.id,
            ),
            value=1,
        ).id,
    ],
)
mutate_150 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="foo",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_153 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="pandas",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_156 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="open",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_159 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r7",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_172 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="x",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_175 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="df",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_176 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="bs",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_177 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="before",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_178 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="altair",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_187 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r1",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_194 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="DataFrame",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_197 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r4",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_198 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="clf",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_200 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r8",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_202 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r9",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_209 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=call_2.id,
            call_id=call_5.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_213 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="obj",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_215 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="my_function",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_220 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="y",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_221 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="e",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_230 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="v",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_233 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=call_1.id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_235 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r6",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_236 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r2",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_240 = MutateNode(
    source_id=call_3.id,
    call_id=call_6.id,
)
mutate_246 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="d",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_249 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="alt",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_251 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="pd",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_253 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="plt",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_266 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="b",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_268 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="img",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_271 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="sns",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_272 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r11",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_273 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="is_new",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_281 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="Decimal",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_283 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="new_df",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_287 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="sklearn.ensemble",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_290 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="types",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_296 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="ls",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_299 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r5",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_302 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="assets",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_305 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="math",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_313 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="PIL.Image",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_315 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r10",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_318 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="a",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_321 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="c",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_326 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="r3",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_330 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="RandomForestClassifier",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
mutate_333 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=GlobalNode(
                                name="decimal",
                                call_id=call_1.id,
                            ).id,
                            call_id=call_4.id,
                        ).id,
                        call_id=call_5.id,
                    ).id,
                    call_id=call_5.id,
                ).id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
