import datetime
from lineapy.data.types import *
from lineapy.utils import get_new_id

session = SessionContext(
    id=get_new_id(),
    environment_type=SessionType.SCRIPT,
    creation_time=datetime.datetime(1, 1, 1, 0, 0),
    file_name="[source file path]",
    code="import lineapy\na = 1\nb = a + 2\nc = 2\nd = 4\ne = d + a\nf = a * b * c\n10\ne\ng = e\n\nlineapy.linea_publish(f, 'f')\n",
    working_directory="dummy_linea_repo/",
    libraries=[
        Library(
            id=get_new_id(),
            name="lineapy",
        ),
    ],
)
import_1 = ImportNode(
    id=get_new_id(),
    session_id=session.id,
    lineno=1,
    col_offset=0,
    end_lineno=1,
    end_col_offset=14,
    library=Library(
        id=get_new_id(),
        name="lineapy",
    ),
)
literal_5 = LiteralNode(
    id=get_new_id(),
    session_id=session.id,
    lineno=8,
    col_offset=0,
    end_lineno=8,
    end_col_offset=2,
    value=10,
)
variable_1 = VariableNode(
    id=get_new_id(),
    session_id=session.id,
    source_node_id=LiteralNode(
        id=get_new_id(),
        session_id=session.id,
        lineno=2,
        col_offset=0,
        end_lineno=2,
        end_col_offset=5,
        value=1,
    ).id,
    assigned_variable_name="a",
)
variable_6 = VariableNode(
    id=get_new_id(),
    session_id=session.id,
    source_node_id=VariableNode(
        id=get_new_id(),
        session_id=session.id,
        lineno=10,
        col_offset=0,
        end_lineno=10,
        end_col_offset=5,
        source_node_id=CallNode(
            id=get_new_id(),
            session_id=session.id,
            lineno=6,
            col_offset=0,
            end_lineno=6,
            end_col_offset=9,
            arguments=[
                ArgumentNode(
                    id=get_new_id(),
                    session_id=session.id,
                    positional_order=0,
                    value_node_id=VariableNode(
                        id=get_new_id(),
                        session_id=session.id,
                        source_node_id=LiteralNode(
                            id=get_new_id(),
                            session_id=session.id,
                            lineno=5,
                            col_offset=0,
                            end_lineno=5,
                            end_col_offset=5,
                            value=4,
                        ).id,
                        assigned_variable_name="d",
                    ).id,
                ).id,
                ArgumentNode(
                    id=get_new_id(),
                    session_id=session.id,
                    positional_order=1,
                    value_node_id=variable_1.id,
                ).id,
            ],
            function_id=LookupNode(
                id=get_new_id(),
                session_id=session.id,
                name="add",
            ).id,
        ).id,
        assigned_variable_name="e",
    ).id,
    assigned_variable_name="g",
)
variable_7 = VariableNode(
    id=get_new_id(),
    session_id=session.id,
    source_node_id=CallNode(
        id=get_new_id(),
        session_id=session.id,
        lineno=7,
        col_offset=0,
        end_lineno=7,
        end_col_offset=13,
        arguments=[
            ArgumentNode(
                id=get_new_id(),
                session_id=session.id,
                positional_order=0,
                value_node_id=CallNode(
                    id=get_new_id(),
                    session_id=session.id,
                    lineno=7,
                    col_offset=4,
                    end_lineno=7,
                    end_col_offset=9,
                    arguments=[
                        ArgumentNode(
                            id=get_new_id(),
                            session_id=session.id,
                            positional_order=0,
                            value_node_id=variable_1.id,
                        ).id,
                        ArgumentNode(
                            id=get_new_id(),
                            session_id=session.id,
                            positional_order=1,
                            value_node_id=VariableNode(
                                id=get_new_id(),
                                session_id=session.id,
                                source_node_id=CallNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    lineno=3,
                                    col_offset=0,
                                    end_lineno=3,
                                    end_col_offset=9,
                                    arguments=[
                                        ArgumentNode(
                                            id=get_new_id(),
                                            session_id=session.id,
                                            positional_order=0,
                                            value_node_id=variable_1.id,
                                        ).id,
                                        ArgumentNode(
                                            id=get_new_id(),
                                            session_id=session.id,
                                            positional_order=1,
                                            value_node_id=LiteralNode(
                                                id=get_new_id(),
                                                session_id=session.id,
                                                lineno=3,
                                                col_offset=8,
                                                end_lineno=3,
                                                end_col_offset=9,
                                                value=2,
                                            ).id,
                                        ).id,
                                    ],
                                    function_id=LookupNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        name="add",
                                    ).id,
                                ).id,
                                assigned_variable_name="b",
                            ).id,
                        ).id,
                    ],
                    function_id=LookupNode(
                        id=get_new_id(),
                        session_id=session.id,
                        name="mul",
                    ).id,
                ).id,
            ).id,
            ArgumentNode(
                id=get_new_id(),
                session_id=session.id,
                positional_order=1,
                value_node_id=VariableNode(
                    id=get_new_id(),
                    session_id=session.id,
                    source_node_id=LiteralNode(
                        id=get_new_id(),
                        session_id=session.id,
                        lineno=4,
                        col_offset=0,
                        end_lineno=4,
                        end_col_offset=5,
                        value=2,
                    ).id,
                    assigned_variable_name="c",
                ).id,
            ).id,
        ],
        function_id=LookupNode(
            id=get_new_id(),
            session_id=session.id,
            name="mul",
        ).id,
    ).id,
    assigned_variable_name="f",
)
