import datetime
from pathlib import *
from lineapy.data.types import *
from lineapy.utils import get_new_id

session = SessionContext(
    id=get_new_id(),
    environment_type=SessionType.SCRIPT,
    creation_time=datetime.datetime(1, 1, 1, 0, 0),
    working_directory="dummy_linea_repo/",
)
source_1 = SourceCode(
    id=get_new_id(),
    code="""import pandas as pd
assert pd.__name__ == \'pandas\'""",
    location=PosixPath("[source file path]"),
)
call_3 = CallNode(
    id=get_new_id(),
    session_id=session.id,
    source_location=SourceLocation(
        lineno=2,
        col_offset=0,
        end_lineno=2,
        end_col_offset=30,
        source_code=source_1.id,
    ),
    arguments=[
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            positional_order=0,
            value_node_id=CallNode(
                id=get_new_id(),
                session_id=session.id,
                source_location=SourceLocation(
                    lineno=2,
                    col_offset=7,
                    end_lineno=2,
                    end_col_offset=30,
                    source_code=source_1.id,
                ),
                arguments=[
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=0,
                        value_node_id=CallNode(
                            id=get_new_id(),
                            session_id=session.id,
                            source_location=SourceLocation(
                                lineno=2,
                                col_offset=7,
                                end_lineno=2,
                                end_col_offset=18,
                                source_code=source_1.id,
                            ),
                            arguments=[
                                ArgumentNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    positional_order=0,
                                    value_node_id=ImportNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        source_location=SourceLocation(
                                            lineno=1,
                                            col_offset=0,
                                            end_lineno=1,
                                            end_col_offset=19,
                                            source_code=source_1.id,
                                        ),
                                        library=Library(
                                            id=get_new_id(),
                                            name="pandas",
                                        ),
                                        alias="pd",
                                    ).id,
                                ).id,
                                ArgumentNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    positional_order=1,
                                    value_node_id=LiteralNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        value="__name__",
                                    ).id,
                                ).id,
                            ],
                            function_id=LookupNode(
                                id=get_new_id(),
                                session_id=session.id,
                                name="getattr",
                            ).id,
                        ).id,
                    ).id,
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=1,
                        value_node_id=LiteralNode(
                            id=get_new_id(),
                            session_id=session.id,
                            source_location=SourceLocation(
                                lineno=2,
                                col_offset=22,
                                end_lineno=2,
                                end_col_offset=30,
                                source_code=source_1.id,
                            ),
                            value="pandas",
                        ).id,
                    ).id,
                ],
                function_id=LookupNode(
                    id=get_new_id(),
                    session_id=session.id,
                    name="eq",
                ).id,
            ).id,
        ).id
    ],
    function_id=LookupNode(
        id=get_new_id(),
        session_id=session.id,
        name="__assert__",
    ).id,
)
