import datetime
from lineapy.data.types import *
from lineapy.utils import get_new_id

session = SessionContext(
    id=get_new_id(),
    environment_type=SessionType.SCRIPT,
    creation_time=datetime.datetime(1, 1, 1, 0, 0),
    file_name="[source file path]",
    code="import lineapy\na = []\nb = 0\nfor x in range(9):\n    a.append(x)\n    b+=x\nx = sum(a)\ny = x + b\nlineapy.linea_publish(y, 'y')\n",
    working_directory="dummy_linea_repo/",
    libraries=[
        Library(
            id=get_new_id(),
            name="lineapy",
        ),
    ],
)
import_1 = ImportNode(
    id=get_new_id(),
    session_id=session.id,
    lineno=1,
    col_offset=0,
    end_lineno=1,
    end_col_offset=14,
    library=Library(
        id=get_new_id(),
        name="lineapy",
    ),
)
variable_1 = VariableNode(
    id=get_new_id(),
    session_id=session.id,
    source_node_id=CallNode(
        id=get_new_id(),
        session_id=session.id,
        lineno=2,
        col_offset=0,
        end_lineno=2,
        end_col_offset=6,
        arguments=[],
        function_id=LookupNode(
            id=get_new_id(),
            session_id=session.id,
            name="__build_list__",
        ).id,
    ).id,
    assigned_variable_name="a",
)
call_2 = CallNode(
    id=get_new_id(),
    session_id=session.id,
    lineno=4,
    col_offset=0,
    end_lineno=6,
    end_col_offset=8,
    arguments=[
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            keyword="a",
            value_node_id=variable_1.id,
        ).id,
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            keyword="b",
            value_node_id=VariableNode(
                id=get_new_id(),
                session_id=session.id,
                source_node_id=LiteralNode(
                    id=get_new_id(),
                    session_id=session.id,
                    lineno=3,
                    col_offset=0,
                    end_lineno=3,
                    end_col_offset=5,
                    value=0,
                ).id,
                assigned_variable_name="b",
            ).id,
        ).id,
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            keyword="range",
            value_node_id=LookupNode(
                id=get_new_id(),
                session_id=session.id,
                name="range",
            ).id,
        ).id,
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            positional_order=0,
            value_node_id=LiteralNode(
                id=get_new_id(),
                session_id=session.id,
                value="for x in range(9):\n    a.append(x)\n    b+=x",
            ).id,
        ).id,
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            positional_order=1,
            value_node_id=LiteralNode(
                id=get_new_id(),
                session_id=session.id,
                value=0,
            ).id,
        ).id,
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            positional_order=2,
            value_node_id=LiteralNode(
                id=get_new_id(),
                session_id=session.id,
                value="x",
            ).id,
        ).id,
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            positional_order=3,
            value_node_id=LiteralNode(
                id=get_new_id(),
                session_id=session.id,
                value="b",
            ).id,
        ).id,
    ],
    function_id=LookupNode(
        id=get_new_id(),
        session_id=session.id,
        name="__exec__",
    ).id,
)
variable_3 = VariableNode(
    id=get_new_id(),
    session_id=session.id,
    source_node_id=CallNode(
        id=get_new_id(),
        session_id=session.id,
        lineno=4,
        col_offset=0,
        end_lineno=6,
        end_col_offset=8,
        arguments=[
            ArgumentNode(
                id=get_new_id(),
                session_id=session.id,
                positional_order=0,
                value_node_id=call_2.id,
            ).id,
            ArgumentNode(
                id=get_new_id(),
                session_id=session.id,
                positional_order=1,
                value_node_id=LiteralNode(
                    id=get_new_id(),
                    session_id=session.id,
                    value=0,
                ).id,
            ).id,
        ],
        function_id=LookupNode(
            id=get_new_id(),
            session_id=session.id,
            name="getitem",
        ).id,
    ).id,
    assigned_variable_name="x",
)
variable_6 = VariableNode(
    id=get_new_id(),
    session_id=session.id,
    source_node_id=CallNode(
        id=get_new_id(),
        session_id=session.id,
        lineno=8,
        col_offset=0,
        end_lineno=8,
        end_col_offset=9,
        arguments=[
            ArgumentNode(
                id=get_new_id(),
                session_id=session.id,
                positional_order=0,
                value_node_id=VariableNode(
                    id=get_new_id(),
                    session_id=session.id,
                    source_node_id=CallNode(
                        id=get_new_id(),
                        session_id=session.id,
                        lineno=7,
                        col_offset=0,
                        end_lineno=7,
                        end_col_offset=10,
                        arguments=[
                            ArgumentNode(
                                id=get_new_id(),
                                session_id=session.id,
                                positional_order=0,
                                value_node_id=variable_1.id,
                            ).id
                        ],
                        function_id=LookupNode(
                            id=get_new_id(),
                            session_id=session.id,
                            name="sum",
                        ).id,
                    ).id,
                    assigned_variable_name="x",
                ).id,
            ).id,
            ArgumentNode(
                id=get_new_id(),
                session_id=session.id,
                positional_order=1,
                value_node_id=VariableNode(
                    id=get_new_id(),
                    session_id=session.id,
                    source_node_id=CallNode(
                        id=get_new_id(),
                        session_id=session.id,
                        lineno=4,
                        col_offset=0,
                        end_lineno=6,
                        end_col_offset=8,
                        arguments=[
                            ArgumentNode(
                                id=get_new_id(),
                                session_id=session.id,
                                positional_order=0,
                                value_node_id=call_2.id,
                            ).id,
                            ArgumentNode(
                                id=get_new_id(),
                                session_id=session.id,
                                positional_order=1,
                                value_node_id=LiteralNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    value=1,
                                ).id,
                            ).id,
                        ],
                        function_id=LookupNode(
                            id=get_new_id(),
                            session_id=session.id,
                            name="getitem",
                        ).id,
                    ).id,
                    assigned_variable_name="b",
                ).id,
            ).id,
        ],
        function_id=LookupNode(
            id=get_new_id(),
            session_id=session.id,
            name="add",
        ).id,
    ).id,
    assigned_variable_name="y",
)
