import datetime
from pathlib import *
from lineapy.data.types import *
from lineapy.utils import get_new_id

source_1 = SourceCode(
    code="""
ls = [1,2,3,4]
ls[0] = 1
a = 4
ls[1] = a
ls[2:3] = [30]
ls[3:a] = [40]
""",
    location=PosixPath("[source file path]"),
)
call_1 = CallNode(
    source_location=SourceLocation(
        lineno=2,
        col_offset=5,
        end_lineno=2,
        end_col_offset=14,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_list",
    ).id,
    positional_args=[
        LiteralNode(
            source_location=SourceLocation(
                lineno=2,
                col_offset=6,
                end_lineno=2,
                end_col_offset=7,
                source_code=source_1.id,
            ),
            value=1,
        ).id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=2,
                col_offset=8,
                end_lineno=2,
                end_col_offset=9,
                source_code=source_1.id,
            ),
            value=2,
        ).id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=2,
                col_offset=10,
                end_lineno=2,
                end_col_offset=11,
                source_code=source_1.id,
            ),
            value=3,
        ).id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=2,
                col_offset=12,
                end_lineno=2,
                end_col_offset=13,
                source_code=source_1.id,
            ),
            value=4,
        ).id,
    ],
)
call_2 = CallNode(
    source_location=SourceLocation(
        lineno=3,
        col_offset=0,
        end_lineno=3,
        end_col_offset=9,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="setitem",
    ).id,
    positional_args=[
        call_1.id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=3,
                col_offset=3,
                end_lineno=3,
                end_col_offset=4,
                source_code=source_1.id,
            ),
            value=0,
        ).id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=3,
                col_offset=8,
                end_lineno=3,
                end_col_offset=9,
                source_code=source_1.id,
            ),
            value=1,
        ).id,
    ],
)
mutate_13 = MutateNode(
    source_id=call_1.id,
    call_id=call_2.id,
)
literal_7 = LiteralNode(
    source_location=SourceLocation(
        lineno=4,
        col_offset=4,
        end_lineno=4,
        end_col_offset=5,
        source_code=source_1.id,
    ),
    value=4,
)
call_3 = CallNode(
    source_location=SourceLocation(
        lineno=5,
        col_offset=0,
        end_lineno=5,
        end_col_offset=9,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="setitem",
    ).id,
    positional_args=[
        mutate_13.id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=5,
                col_offset=3,
                end_lineno=5,
                end_col_offset=4,
                source_code=source_1.id,
            ),
            value=1,
        ).id,
        literal_7.id,
    ],
)
mutate_61 = MutateNode(
    source_id=MutateNode(
        source_id=mutate_13.id,
        call_id=call_3.id,
    ).id,
    call_id=call_3.id,
)
call_5 = CallNode(
    source_location=SourceLocation(
        lineno=6,
        col_offset=10,
        end_lineno=6,
        end_col_offset=14,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_list",
    ).id,
    positional_args=[
        LiteralNode(
            source_location=SourceLocation(
                lineno=6,
                col_offset=11,
                end_lineno=6,
                end_col_offset=13,
                source_code=source_1.id,
            ),
            value=30,
        ).id
    ],
)
call_6 = CallNode(
    source_location=SourceLocation(
        lineno=6,
        col_offset=0,
        end_lineno=6,
        end_col_offset=14,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="setitem",
    ).id,
    positional_args=[
        mutate_61.id,
        CallNode(
            source_location=SourceLocation(
                lineno=6,
                col_offset=3,
                end_lineno=6,
                end_col_offset=6,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="slice",
            ).id,
            positional_args=[
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=6,
                        col_offset=3,
                        end_lineno=6,
                        end_col_offset=4,
                        source_code=source_1.id,
                    ),
                    value=2,
                ).id,
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=6,
                        col_offset=5,
                        end_lineno=6,
                        end_col_offset=6,
                        source_code=source_1.id,
                    ),
                    value=3,
                ).id,
            ],
        ).id,
        call_5.id,
    ],
)
mutate_129 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=mutate_61.id,
                call_id=call_6.id,
            ).id,
            call_id=call_6.id,
        ).id,
        call_id=call_6.id,
    ).id,
    call_id=call_6.id,
)
call_9 = CallNode(
    source_location=SourceLocation(
        lineno=7,
        col_offset=0,
        end_lineno=7,
        end_col_offset=14,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="setitem",
    ).id,
    positional_args=[
        mutate_129.id,
        CallNode(
            source_location=SourceLocation(
                lineno=7,
                col_offset=3,
                end_lineno=7,
                end_col_offset=6,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="slice",
            ).id,
            positional_args=[
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=7,
                        col_offset=3,
                        end_lineno=7,
                        end_col_offset=4,
                        source_code=source_1.id,
                    ),
                    value=3,
                ).id,
                literal_7.id,
            ],
        ).id,
        CallNode(
            source_location=SourceLocation(
                lineno=7,
                col_offset=10,
                end_lineno=7,
                end_col_offset=14,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="l_list",
            ).id,
            positional_args=[
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=7,
                        col_offset=11,
                        end_lineno=7,
                        end_col_offset=13,
                        source_code=source_1.id,
                    ),
                    value=40,
                ).id
            ],
        ).id,
    ],
)
mutate_234 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="math",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_235 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="my_function",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_236 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="x",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_243 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="DataFrame",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_250 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="open",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_273 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="bs",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_274 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r6",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_280 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="pandas",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_284 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r5",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_290 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r10",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_317 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r8",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_325 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="a",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_327 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="pd",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_329 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=mutate_129.id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_330 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="v",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_346 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r7",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_351 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r3",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_357 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="df",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_364 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r11",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_370 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="img",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_388 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="b",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_389 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r9",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_398 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="c",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_401 = MutateNode(
    source_id=call_5.id,
    call_id=call_9.id,
)
mutate_414 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="plt",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_417 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="new_df",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_419 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r1",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_431 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r4",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_435 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="PIL.Image",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_444 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="foo",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
mutate_451 = MutateNode(
    source_id=MutateNode(
        source_id=MutateNode(
            source_id=MutateNode(
                source_id=MutateNode(
                    source_id=MutateNode(
                        source_id=MutateNode(
                            source_id=MutateNode(
                                source_id=MutateNode(
                                    source_id=MutateNode(
                                        source_id=MutateNode(
                                            source_id=MutateNode(
                                                source_id=MutateNode(
                                                    source_id=MutateNode(
                                                        source_id=MutateNode(
                                                            source_id=GlobalNode(
                                                                name="r2",
                                                                call_id=call_1.id,
                                                            ).id,
                                                            call_id=call_2.id,
                                                        ).id,
                                                        call_id=call_3.id,
                                                    ).id,
                                                    call_id=call_3.id,
                                                ).id,
                                                call_id=call_6.id,
                                            ).id,
                                            call_id=call_6.id,
                                        ).id,
                                        call_id=call_6.id,
                                    ).id,
                                    call_id=call_6.id,
                                ).id,
                                call_id=call_9.id,
                            ).id,
                            call_id=call_9.id,
                        ).id,
                        call_id=call_9.id,
                    ).id,
                    call_id=call_9.id,
                ).id,
                call_id=call_9.id,
            ).id,
            call_id=call_9.id,
        ).id,
        call_id=call_9.id,
    ).id,
    call_id=call_9.id,
)
