import datetime
from lineapy.data.types import *
from lineapy.utils import get_new_id

session = SessionContext(
    id=get_new_id(),
    environment_type=SessionType.SCRIPT,
    creation_time=datetime.datetime(1, 1, 1, 0, 0),
    file_name="[source file path]",
    code="from pandas import DataFrame\nv = 4\ndf = DataFrame([[1,2], [3,v]])\ndf[0].astype(str)\nassert df.size == 4\nnew_df = df.iloc[:, 1]\nassert new_df.size == 2\n",
    working_directory="dummy_linea_repo/",
    libraries=[
        Library(
            id=get_new_id(),
            name="pandas",
        ),
    ],
)
variable_3 = VariableNode(
    id=get_new_id(),
    session_id=session.id,
    source_node_id=CallNode(
        id=get_new_id(),
        session_id=session.id,
        lineno=3,
        col_offset=0,
        end_lineno=3,
        end_col_offset=30,
        arguments=[
            ArgumentNode(
                id=get_new_id(),
                session_id=session.id,
                positional_order=0,
                value_node_id=CallNode(
                    id=get_new_id(),
                    session_id=session.id,
                    lineno=3,
                    col_offset=15,
                    end_lineno=3,
                    end_col_offset=29,
                    arguments=[
                        ArgumentNode(
                            id=get_new_id(),
                            session_id=session.id,
                            positional_order=0,
                            value_node_id=CallNode(
                                id=get_new_id(),
                                session_id=session.id,
                                lineno=3,
                                col_offset=16,
                                end_lineno=3,
                                end_col_offset=21,
                                arguments=[
                                    ArgumentNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        positional_order=0,
                                        value_node_id=LiteralNode(
                                            id=get_new_id(),
                                            session_id=session.id,
                                            lineno=3,
                                            col_offset=17,
                                            end_lineno=3,
                                            end_col_offset=18,
                                            value=1,
                                        ).id,
                                    ).id,
                                    ArgumentNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        positional_order=1,
                                        value_node_id=LiteralNode(
                                            id=get_new_id(),
                                            session_id=session.id,
                                            lineno=3,
                                            col_offset=19,
                                            end_lineno=3,
                                            end_col_offset=20,
                                            value=2,
                                        ).id,
                                    ).id,
                                ],
                                function_id=LookupNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    name="__build_list__",
                                ).id,
                            ).id,
                        ).id,
                        ArgumentNode(
                            id=get_new_id(),
                            session_id=session.id,
                            positional_order=1,
                            value_node_id=CallNode(
                                id=get_new_id(),
                                session_id=session.id,
                                lineno=3,
                                col_offset=23,
                                end_lineno=3,
                                end_col_offset=28,
                                arguments=[
                                    ArgumentNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        positional_order=0,
                                        value_node_id=LiteralNode(
                                            id=get_new_id(),
                                            session_id=session.id,
                                            lineno=3,
                                            col_offset=24,
                                            end_lineno=3,
                                            end_col_offset=25,
                                            value=3,
                                        ).id,
                                    ).id,
                                    ArgumentNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        positional_order=1,
                                        value_node_id=VariableNode(
                                            id=get_new_id(),
                                            session_id=session.id,
                                            source_node_id=LiteralNode(
                                                id=get_new_id(),
                                                session_id=session.id,
                                                lineno=2,
                                                col_offset=0,
                                                end_lineno=2,
                                                end_col_offset=5,
                                                value=4,
                                            ).id,
                                            assigned_variable_name="v",
                                        ).id,
                                    ).id,
                                ],
                                function_id=LookupNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    name="__build_list__",
                                ).id,
                            ).id,
                        ).id,
                    ],
                    function_id=LookupNode(
                        id=get_new_id(),
                        session_id=session.id,
                        name="__build_list__",
                    ).id,
                ).id,
            ).id
        ],
        function_id=VariableNode(
            id=get_new_id(),
            session_id=session.id,
            source_node_id=CallNode(
                id=get_new_id(),
                session_id=session.id,
                arguments=[
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=0,
                        value_node_id=ImportNode(
                            id=get_new_id(),
                            session_id=session.id,
                            lineno=1,
                            col_offset=0,
                            end_lineno=1,
                            end_col_offset=28,
                            library=Library(
                                id=get_new_id(),
                                name="pandas",
                            ),
                            attributes={"DataFrame": "DataFrame"},
                        ).id,
                    ).id,
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=1,
                        value_node_id=LiteralNode(
                            id=get_new_id(),
                            session_id=session.id,
                            value="DataFrame",
                        ).id,
                    ).id,
                ],
                function_id=LookupNode(
                    id=get_new_id(),
                    session_id=session.id,
                    name="getattr",
                ).id,
            ).id,
            assigned_variable_name="DataFrame",
        ).id,
    ).id,
    assigned_variable_name="df",
)
call_8 = CallNode(
    id=get_new_id(),
    session_id=session.id,
    lineno=4,
    col_offset=0,
    end_lineno=4,
    end_col_offset=17,
    arguments=[
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            positional_order=0,
            value_node_id=LookupNode(
                id=get_new_id(),
                session_id=session.id,
                name="str",
            ).id,
        ).id
    ],
    function_id=CallNode(
        id=get_new_id(),
        session_id=session.id,
        lineno=4,
        col_offset=0,
        end_lineno=4,
        end_col_offset=12,
        arguments=[
            ArgumentNode(
                id=get_new_id(),
                session_id=session.id,
                positional_order=0,
                value_node_id=CallNode(
                    id=get_new_id(),
                    session_id=session.id,
                    lineno=4,
                    col_offset=0,
                    end_lineno=4,
                    end_col_offset=5,
                    arguments=[
                        ArgumentNode(
                            id=get_new_id(),
                            session_id=session.id,
                            positional_order=0,
                            value_node_id=variable_3.id,
                        ).id,
                        ArgumentNode(
                            id=get_new_id(),
                            session_id=session.id,
                            positional_order=1,
                            value_node_id=LiteralNode(
                                id=get_new_id(),
                                session_id=session.id,
                                lineno=4,
                                col_offset=3,
                                end_lineno=4,
                                end_col_offset=4,
                                value=0,
                            ).id,
                        ).id,
                    ],
                    function_id=LookupNode(
                        id=get_new_id(),
                        session_id=session.id,
                        name="getitem",
                    ).id,
                ).id,
            ).id,
            ArgumentNode(
                id=get_new_id(),
                session_id=session.id,
                positional_order=1,
                value_node_id=LiteralNode(
                    id=get_new_id(),
                    session_id=session.id,
                    value="astype",
                ).id,
            ).id,
        ],
        function_id=LookupNode(
            id=get_new_id(),
            session_id=session.id,
            name="getattr",
        ).id,
    ).id,
)
call_11 = CallNode(
    id=get_new_id(),
    session_id=session.id,
    lineno=5,
    col_offset=0,
    end_lineno=5,
    end_col_offset=19,
    arguments=[
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            positional_order=0,
            value_node_id=CallNode(
                id=get_new_id(),
                session_id=session.id,
                lineno=5,
                col_offset=7,
                end_lineno=5,
                end_col_offset=19,
                arguments=[
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=0,
                        value_node_id=CallNode(
                            id=get_new_id(),
                            session_id=session.id,
                            lineno=5,
                            col_offset=7,
                            end_lineno=5,
                            end_col_offset=14,
                            arguments=[
                                ArgumentNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    positional_order=0,
                                    value_node_id=variable_3.id,
                                ).id,
                                ArgumentNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    positional_order=1,
                                    value_node_id=LiteralNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        value="size",
                                    ).id,
                                ).id,
                            ],
                            function_id=LookupNode(
                                id=get_new_id(),
                                session_id=session.id,
                                name="getattr",
                            ).id,
                        ).id,
                    ).id,
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=1,
                        value_node_id=LiteralNode(
                            id=get_new_id(),
                            session_id=session.id,
                            lineno=5,
                            col_offset=18,
                            end_lineno=5,
                            end_col_offset=19,
                            value=4,
                        ).id,
                    ).id,
                ],
                function_id=LookupNode(
                    id=get_new_id(),
                    session_id=session.id,
                    name="eq",
                ).id,
            ).id,
        ).id
    ],
    function_id=LookupNode(
        id=get_new_id(),
        session_id=session.id,
        name="__assert__",
    ).id,
)
call_18 = CallNode(
    id=get_new_id(),
    session_id=session.id,
    lineno=7,
    col_offset=0,
    end_lineno=7,
    end_col_offset=23,
    arguments=[
        ArgumentNode(
            id=get_new_id(),
            session_id=session.id,
            positional_order=0,
            value_node_id=CallNode(
                id=get_new_id(),
                session_id=session.id,
                lineno=7,
                col_offset=7,
                end_lineno=7,
                end_col_offset=23,
                arguments=[
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=0,
                        value_node_id=CallNode(
                            id=get_new_id(),
                            session_id=session.id,
                            lineno=7,
                            col_offset=7,
                            end_lineno=7,
                            end_col_offset=18,
                            arguments=[
                                ArgumentNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    positional_order=0,
                                    value_node_id=VariableNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        source_node_id=CallNode(
                                            id=get_new_id(),
                                            session_id=session.id,
                                            lineno=6,
                                            col_offset=0,
                                            end_lineno=6,
                                            end_col_offset=22,
                                            arguments=[
                                                ArgumentNode(
                                                    id=get_new_id(),
                                                    session_id=session.id,
                                                    positional_order=0,
                                                    value_node_id=CallNode(
                                                        id=get_new_id(),
                                                        session_id=session.id,
                                                        lineno=6,
                                                        col_offset=9,
                                                        end_lineno=6,
                                                        end_col_offset=16,
                                                        arguments=[
                                                            ArgumentNode(
                                                                id=get_new_id(),
                                                                session_id=session.id,
                                                                positional_order=0,
                                                                value_node_id=variable_3.id,
                                                            ).id,
                                                            ArgumentNode(
                                                                id=get_new_id(),
                                                                session_id=session.id,
                                                                positional_order=1,
                                                                value_node_id=LiteralNode(
                                                                    id=get_new_id(),
                                                                    session_id=session.id,
                                                                    value="iloc",
                                                                ).id,
                                                            ).id,
                                                        ],
                                                        function_id=LookupNode(
                                                            id=get_new_id(),
                                                            session_id=session.id,
                                                            name="getattr",
                                                        ).id,
                                                    ).id,
                                                ).id,
                                                ArgumentNode(
                                                    id=get_new_id(),
                                                    session_id=session.id,
                                                    positional_order=1,
                                                    value_node_id=CallNode(
                                                        id=get_new_id(),
                                                        session_id=session.id,
                                                        lineno=6,
                                                        col_offset=17,
                                                        end_lineno=6,
                                                        end_col_offset=21,
                                                        arguments=[
                                                            ArgumentNode(
                                                                id=get_new_id(),
                                                                session_id=session.id,
                                                                positional_order=0,
                                                                value_node_id=CallNode(
                                                                    id=get_new_id(),
                                                                    session_id=session.id,
                                                                    lineno=6,
                                                                    col_offset=17,
                                                                    end_lineno=6,
                                                                    end_col_offset=18,
                                                                    arguments=[
                                                                        ArgumentNode(
                                                                            id=get_new_id(),
                                                                            session_id=session.id,
                                                                            positional_order=0,
                                                                            value_node_id=LiteralNode(
                                                                                id=get_new_id(),
                                                                                session_id=session.id,
                                                                            ).id,
                                                                        ).id
                                                                    ],
                                                                    function_id=LookupNode(
                                                                        id=get_new_id(),
                                                                        session_id=session.id,
                                                                        name="slice",
                                                                    ).id,
                                                                ).id,
                                                            ).id,
                                                            ArgumentNode(
                                                                id=get_new_id(),
                                                                session_id=session.id,
                                                                positional_order=1,
                                                                value_node_id=LiteralNode(
                                                                    id=get_new_id(),
                                                                    session_id=session.id,
                                                                    lineno=6,
                                                                    col_offset=20,
                                                                    end_lineno=6,
                                                                    end_col_offset=21,
                                                                    value=1,
                                                                ).id,
                                                            ).id,
                                                        ],
                                                        function_id=LookupNode(
                                                            id=get_new_id(),
                                                            session_id=session.id,
                                                            name="__build_tuple__",
                                                        ).id,
                                                    ).id,
                                                ).id,
                                            ],
                                            function_id=LookupNode(
                                                id=get_new_id(),
                                                session_id=session.id,
                                                name="getitem",
                                            ).id,
                                        ).id,
                                        assigned_variable_name="new_df",
                                    ).id,
                                ).id,
                                ArgumentNode(
                                    id=get_new_id(),
                                    session_id=session.id,
                                    positional_order=1,
                                    value_node_id=LiteralNode(
                                        id=get_new_id(),
                                        session_id=session.id,
                                        value="size",
                                    ).id,
                                ).id,
                            ],
                            function_id=LookupNode(
                                id=get_new_id(),
                                session_id=session.id,
                                name="getattr",
                            ).id,
                        ).id,
                    ).id,
                    ArgumentNode(
                        id=get_new_id(),
                        session_id=session.id,
                        positional_order=1,
                        value_node_id=LiteralNode(
                            id=get_new_id(),
                            session_id=session.id,
                            lineno=7,
                            col_offset=22,
                            end_lineno=7,
                            end_col_offset=23,
                            value=2,
                        ).id,
                    ).id,
                ],
                function_id=LookupNode(
                    id=get_new_id(),
                    session_id=session.id,
                    name="eq",
                ).id,
            ).id,
        ).id
    ],
    function_id=LookupNode(
        id=get_new_id(),
        session_id=session.id,
        name="__assert__",
    ).id,
)
