import datetime
from pathlib import *
from lineapy.data.types import *
from lineapy.utils.utils import get_new_id

source_1 = SourceCode(
    code="""import lineapy
y = lineapy.get(\'x\').value + 10
lineapy.save(y, \'y\')
""",
    location=PosixPath("[source file path]"),
)
import_1 = ImportNode(
    source_location=SourceLocation(
        lineno=1,
        col_offset=0,
        end_lineno=1,
        end_col_offset=14,
        source_code=source_1.id,
    ),
    name="lineapy",
    version="0.0.1",
    package_name="lineapy",
)
call_6 = CallNode(
    source_location=SourceLocation(
        lineno=3,
        col_offset=0,
        end_lineno=3,
        end_col_offset=20,
        source_code=source_1.id,
    ),
    function_id=CallNode(
        source_location=SourceLocation(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=12,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="getattr",
        ).id,
        positional_args=[
            import_1.id,
            LiteralNode(
                value="save",
            ).id,
        ],
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=2,
                col_offset=4,
                end_lineno=2,
                end_col_offset=31,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="add",
            ).id,
            positional_args=[
                CallNode(
                    source_location=SourceLocation(
                        lineno=2,
                        col_offset=4,
                        end_lineno=2,
                        end_col_offset=26,
                        source_code=source_1.id,
                    ),
                    function_id=LookupNode(
                        name="getattr",
                    ).id,
                    positional_args=[
                        CallNode(
                            source_location=SourceLocation(
                                lineno=2,
                                col_offset=4,
                                end_lineno=2,
                                end_col_offset=20,
                                source_code=source_1.id,
                            ),
                            function_id=CallNode(
                                source_location=SourceLocation(
                                    lineno=2,
                                    col_offset=4,
                                    end_lineno=2,
                                    end_col_offset=15,
                                    source_code=source_1.id,
                                ),
                                function_id=LookupNode(
                                    name="getattr",
                                ).id,
                                positional_args=[
                                    import_1.id,
                                    LiteralNode(
                                        value="get",
                                    ).id,
                                ],
                            ).id,
                            positional_args=[
                                LiteralNode(
                                    source_location=SourceLocation(
                                        lineno=2,
                                        col_offset=16,
                                        end_lineno=2,
                                        end_col_offset=19,
                                        source_code=source_1.id,
                                    ),
                                    value="x",
                                ).id
                            ],
                        ).id,
                        LiteralNode(
                            value="value",
                        ).id,
                    ],
                ).id,
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=2,
                        col_offset=29,
                        end_lineno=2,
                        end_col_offset=31,
                        source_code=source_1.id,
                    ),
                    value=10,
                ).id,
            ],
        ).id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=3,
                col_offset=16,
                end_lineno=3,
                end_col_offset=19,
                source_code=source_1.id,
            ),
            value="y",
        ).id,
    ],
)
