#!/usr/bin/env python
# coding: utf-8

# taken from https://www.kaggle.com/shrutimechlearn/step-by-step-diabetes-classification-knn-detailed/notebook

# In[1]:

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

import lineapy

sns.set()
import warnings

warnings.filterwarnings("ignore")
# get_ipython().run_line_magic("matplotlib", "inline")
# plt.style.use('ggplot')
# ggplot is R based visualisation package that provides better graphics with higher level of abstraction

# Turn on interactive mode for now so figures don't block.
plt.ion()


# ## Basic Data Science and ML Pipeline

# ## OSEMN Pipeline
# * O - Obtaining our data
# * S - Scrubbing / Cleaning our data
# * E - Exploring / Visualizing our data will allow us to find patterns and trends
# * M - Modeling our data will give us our predictive power as a wizard
# * N - INterpreting our data
#
#
# For reference : https://www.linkedin.com/pulse/life-data-science-osemn-randy-lao/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_post_details%3BmDlg5VsdSBCLBps2R0vRZA%3D%3D

# In[2]:


# Loading the dataset
diabetes_data = pd.read_csv("./data/diabetes.csv")

# Print the first 5 rows of the dataframe.
diabetes_data.head()


# ## Basic EDA and statistical analysis
#

# In[3]:


## gives information about the data types,columns, null value counts, memory usage etc
## function reference : https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.info.html
diabetes_data.info(verbose=True)


# **DataFrame.describe()** method generates descriptive statistics that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding NaN values. This method tells us a lot of things about a dataset. One important thing is that the describe() method deals only with numeric values. It doesn't work with any categorical values. So if there are any categorical values in a column the describe() method will ignore it and display summary for the other columns unless parameter include="all" is passed.
#
# Now, let's understand the statistics that are generated by the describe() method:
# * count tells us the number of NoN-empty rows in a feature.
# * mean tells us the mean value of that feature.
# * std tells us the Standard Deviation Value of that feature.
# * min tells us the minimum value of that feature.
# * 25%, 50%, and 75% are the percentile/quartile of each features. This quartile information helps us to detect Outliers.
# * max tells us the maximum value of that feature.

# In[4]:


## basic statistic details about the data (note only numerical columns would be displayed here unless parameter include="all")
## for reference: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.describe.html#pandas.DataFrame.describe
diabetes_data.describe()

## Also see :
##to return columns of a specific dtype: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes


# In[5]:


diabetes_data.describe().T


# ### The Question creeping out of this summary
#
# #### Can minimum value of below listed columns be zero (0)?
#
# On these columns, a value of zero does not make sense and thus indicates missing value.
#
# Following columns or variables have an invalid zero value:
# 1. Glucose
# 2. BloodPressure
# 3. SkinThickness
# 4. Insulin
# 5. BMI

# #### It is better to replace zeros with nan since after that counting them would be easier and zeros need to be replaced with suitable values

# In[6]:


diabetes_data_copy = diabetes_data.copy(deep=True)
diabetes_data_copy[
    ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
] = diabetes_data_copy[
    ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
].replace(
    0, np.NaN
)

## showing the count of Nans
print(diabetes_data_copy.isnull().sum())


# #### To fill these Nan values the data distribution needs to be understood

# In[7]:


p = diabetes_data.hist(figsize=(20, 20))


# ### Aiming to impute nan values for the columns in accordance with their distribution

# In[8]:


diabetes_data_copy["Glucose"].fillna(
    diabetes_data_copy["Glucose"].mean(), inplace=True
)
diabetes_data_copy["BloodPressure"].fillna(
    diabetes_data_copy["BloodPressure"].mean(), inplace=True
)
diabetes_data_copy["SkinThickness"].fillna(
    diabetes_data_copy["SkinThickness"].median(), inplace=True
)
diabetes_data_copy["Insulin"].fillna(
    diabetes_data_copy["Insulin"].median(), inplace=True
)
diabetes_data_copy["BMI"].fillna(
    diabetes_data_copy["BMI"].median(), inplace=True
)


# ## Plotting after Nan removal

# In[9]:


p = diabetes_data_copy.hist(figsize=(20, 20))


# ## Skewness
#
# A ***left-skewed distribution*** has a long left tail. Left-skewed distributions are also called negatively-skewed distributions. That’s because there is a long tail in the negative direction on the number line. The mean is also to the left of the peak.
#
# A ***right-skewed distribution*** has a long right tail. Right-skewed distributions are also called positive-skew distributions. That’s because there is a long tail in the positive direction on the number line. The mean is also to the right of the peak.
#
#
# ![](https://www.statisticshowto.datasciencecentral.com/wp-content/uploads/2014/02/pearson-mode-skewness.jpg)
#
#
# #### to learn more about skewness
# https://www.statisticshowto.datasciencecentral.com/probability-and-statistics/skewed-distribution/

# In[10]:


## observing the shape of the data
diabetes_data.shape


# In[11]:


## data type analysis
# plt.figure(figsize=(5,5))
# sns.set(font_scale=2)
sns.countplot(y=diabetes_data.dtypes, data=diabetes_data)
plt.xlabel("count of each data type")
plt.ylabel("data types")
plt.show()


# In[12]:


## null count analysis
# import missingno as msno

# p = msno.bar(diabetes_data)


# In[13]:


## checking the balance of the data by plotting the count of outcomes by their value
color_wheel = {1: "#0392cf", 2: "#7bc043"}
colors = diabetes_data["Outcome"].map(lambda x: color_wheel.get(x + 1))
print(diabetes_data.Outcome.value_counts())
p = diabetes_data.Outcome.value_counts().plot(kind="bar")


# #### The above graph shows that the data is biased towards datapoints having outcome value as 0 where it means that diabetes was not present actually. The number of non-diabetics is almost twice the number of diabetic patients

# #### Scatter matrix of uncleaned data

# In[14]:


from pandas.tools.plotting import scatter_matrix

p = scatter_matrix(diabetes_data, figsize=(25, 25))


# ###### The pairs plot builds on two basic figures, the histogram and the scatter plot. The histogram on the diagonal allows us to see the distribution of a single variable while the scatter plots on the upper and lower triangles show the relationship (or lack thereof) between two variables.
#
# For Reference: https://towardsdatascience.com/visualizing-data-with-pair-plots-in-python-f228cf529166

# #### Pair plot for clean data

# In[15]:


p = sns.pairplot(diabetes_data_copy, hue="Outcome")


# ***Pearson's Correlation Coefficient***: helps you find out the relationship between two quantities. It gives you the measure of the strength of association between two variables. The value of Pearson's Correlation Coefficient can be between -1 to +1. 1 means that they are highly correlated and 0 means no correlation.
#
# A heat map is a two-dimensional representation of information with the help of colors. Heat maps can help the user visualize simple or complex information.

# #### Heatmap for unclean data

# In[16]:


plt.figure(
    figsize=(12, 10)
)  # on this line I just set the size of figure to 12 by 10.
p = sns.heatmap(
    diabetes_data.corr(), annot=True, cmap="RdYlGn"
)  # seaborn has very simple solution for heatmap


# #### Heatmap for clean data

# In[17]:


plt.figure(
    figsize=(12, 10)
)  # on this line I just set the size of figure to 12 by 10.
p = sns.heatmap(
    diabetes_data_copy.corr(), annot=True, cmap="RdYlGn"
)  # seaborn has very simple solution for heatmap


# ## Scaling the data
# data Z is rescaled such that μ = 0 and 𝛔 = 1, and is done through this formula:
# ![](https://cdn-images-1.medium.com/max/800/0*PXGPVYIxyI_IEHP7.)
#
#
# #### to learn more about scaling techniques
# https://medium.com/@rrfd/standardize-or-normalize-examples-in-python-e3f174b65dfc
# https://machinelearningmastery.com/rescaling-data-for-machine-learning-in-python-with-scikit-learn/

# In[18]:


from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X = pd.DataFrame(
    sc_X.fit_transform(
        diabetes_data_copy.drop(["Outcome"], axis=1),
    ),
    columns=[
        "Pregnancies",
        "Glucose",
        "BloodPressure",
        "SkinThickness",
        "Insulin",
        "BMI",
        "DiabetesPedigreeFunction",
        "Age",
    ],
)


# In[19]:


X.head()


# In[20]:


# X = diabetes_data.drop("Outcome",axis = 1)
y = diabetes_data_copy.Outcome


# ### Why Scaling the data for KNN?

# #### it is always advisable to bring all the features to the same scale for applying distance based algorithms like KNN.
# ##### Let's see an example of distance calculation using two features whose magnitudes/ranges vary greatly.
# Euclidean Distance = [(100000–80000)^2 + (30–25)^2]^(1/2)

# #### We can imagine how the feature with greater range with overshadow or dimenish the smaller feature completely and this will impact the performance of all distance based model as it will give higher weightage to variables which have higher magnitude.

# ## Test Train Split and Cross Validation methods
#
#
#
# ***Train Test Split*** : To have unknown datapoints to test the data rather than testing with the same points with which the model was trained. This helps capture the model performance much better.
#
# ![](https://cdn-images-1.medium.com/max/1600/1*-8_kogvwmL1H6ooN1A1tsQ.png)
#
# ***Cross Validation***: When model is split into training and testing it can be possible that specific type of data point may go entirely into either training or testing portion. This would lead the model to perform poorly. Hence over-fitting and underfitting problems can be well avoided with cross validation techniques
#
# ![](https://cdn-images-1.medium.com/max/1600/1*4G__SV580CxFj78o9yUXuQ.png)
#
#
# ***About Stratify*** : Stratify parameter makes a split so that the proportion of values in the sample produced will be the same as the proportion of values provided to parameter stratify.
#
# For example, if variable y is a binary categorical variable with values 0 and 1 and there are 25% of zeros and 75% of ones, stratify=y will make sure that your random split has 25% of 0's and 75% of 1's.
#
# For Reference : https://towardsdatascience.com/train-test-split-and-cross-validation-in-python-80b61beca4b6

# In[21]:


# importing train_test_split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=1 / 3, random_state=42, stratify=y
)


# In[22]:


from sklearn.neighbors import KNeighborsClassifier

test_scores = []
train_scores = []

for i in range(1, 15):

    knn = KNeighborsClassifier(i)
    knn.fit(X_train, y_train)

    train_scores.append(knn.score(X_train, y_train))
    test_scores.append(knn.score(X_test, y_test))


# In[23]:


## score that comes from testing on the same datapoints that were used for training
max_train_score = max(train_scores)
train_scores_ind = [
    i for i, v in enumerate(train_scores) if v == max_train_score
]
print(
    "Max train score {} % and k = {}".format(
        max_train_score * 100, list(map(lambda x: x + 1, train_scores_ind))
    )
)


# In[24]:


## score that comes from testing on the datapoints that were split in the beginning to be used for testing solely
max_test_score = max(test_scores)
test_scores_ind = [i for i, v in enumerate(test_scores) if v == max_test_score]
print(
    "Max test score {} % and k = {}".format(
        max_test_score * 100, list(map(lambda x: x + 1, test_scores_ind))
    )
)


# ## Result Visualisation

# In[25]:


plt.figure(figsize=(12, 5))
p = sns.lineplot(range(1, 15), train_scores, marker="*", label="Train Score")
p = sns.lineplot(range(1, 15), test_scores, marker="o", label="Test Score")


# #### The best result is captured at k = 11 hence 11 is used for the final model

# In[26]:


# Setup a knn classifier with k neighbors
knn = KNeighborsClassifier(11)

knn.fit(X_train, y_train)
knn.score(X_test, y_test)


# In[27]:


## trying to plot decision boundary


# In[28]:


# # Model Performance Analysis

# ## 1. Confusion Matrix
#
# The confusion matrix is a technique used for summarizing the performance of a classification algorithm i.e. it has binary outputs.
# ![](https://cdn-images-1.medium.com/max/1600/0*-GAP6jhtJvt7Bqiv.png)
#
#
#
# ### ***In the famous cancer example***:
#
#
# ###### Cases in which the doctor predicted YES (they have the disease), and they do have the disease will be termed as TRUE POSITIVES (TP). The doctor has correctly predicted that the patient has the disease.
#
# ###### Cases in which the doctor predicted NO (they do not have the disease), and they don’t have the disease will be termed as TRUE NEGATIVES (TN). The doctor has correctly predicted that the patient does not have the disease.
#
# ###### Cases in which the doctor predicted YES, and they do not have the disease will be termed as FALSE POSITIVES (FP). Also known as “Type I error”.
#
# ###### Cases in which the doctor predicted NO, and they have the disease will be termed as FALSE NEGATIVES (FN). Also known as “Type II error”.
#
# ![](https://cdn-images-1.medium.com/max/1600/0*9r99oJ2PTRi4gYF_.jpg)
#
# For Reference: https://medium.com/@djocz/confusion-matrix-aint-that-confusing-d29e18403327

# In[29]:


# import confusion_matrix
from sklearn.metrics import confusion_matrix

# let us get the predictions using the classifier we had fit above
y_pred = knn.predict(X_test)
confusion_matrix(y_test, y_pred)
pd.crosstab(
    y_test, y_pred, rownames=["True"], colnames=["Predicted"], margins=True
)


# In[30]:


y_pred = knn.predict(X_test)
from sklearn import metrics

cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
p = sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap="YlGnBu", fmt="g")
plt.title("Confusion matrix", y=1.1)
plt.ylabel("Actual label")
plt.xlabel("Predicted label")


# ## 2. Classification Report
#
# Report which includes Precision, Recall and F1-Score.
#
#
# #### Precision Score
#         TP – True Positives
#         FP – False Positives
#
#         Precision – Accuracy of positive predictions.
#         Precision = TP/(TP + FP)
#
#
# #### Recall Score
#         FN – False Negatives
#
#         Recall(sensitivity or true positive rate): Fraction of positives that were correctly identified.
#         Recall = TP/(TP+FN)
#
# #### F1 Score
#         F1 Score (aka F-Score or F-Measure) – A helpful metric for comparing two classifiers.
#         F1 Score takes into account precision and the recall.
#         It is created by finding the the harmonic mean of precision and recall.
#
#         F1 = 2 x (precision x recall)/(precision + recall)
#
#
#
# > > ***Precision*** - Precision is the ratio of correctly predicted positive observations to the total predicted positive observations. The question that this metric answer is of all passengers that labeled as survived, how many actually survived? High precision relates to the low false positive rate. We have got 0.788 precision which is pretty good.
# > >
# > > Precision = TP/TP+FP
# > >
# > > ***Recall (Sensitivity)*** - Recall is the ratio of correctly predicted positive observations to the all observations in actual class - yes. The question recall answers is: Of all the passengers that truly survived, how many did we label? A recall greater than 0.5 is good.
# > >
# > > Recall = TP/TP+FN
# > >
# > > ***F1 score*** - F1 Score is the weighted average of Precision and Recall. Therefore, this score takes both false positives and false negatives into account. Intuitively it is not as easy to understand as accuracy, but F1 is usually more useful than accuracy, especially if you have an uneven class distribution. Accuracy works best if false positives and false negatives have similar cost. If the cost of false positives and false negatives are very different, it’s better to look at both Precision and Recall.
# > >
# > > F1 Score = 2*(Recall * Precision) / (Recall + Precision)
#
#
# For Reference: http://joshlawman.com/metrics-classification-report-breakdown-precision-recall-f1/
#                         : https://blog.exsilio.com/all/accuracy-precision-recall-f1-score-interpretation-of-performance-measures/

# In[31]:


# import classification_report
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
lineapy.save(report, "classification_report")


# ## 3. ROC - AUC
# ROC (Receiver Operating Characteristic) Curve tells us about how good the model can distinguish between two things (e.g If a patient has a disease or no). Better models can accurately distinguish between the two. Whereas, a poor model will have difficulties in distinguishing between the two
#
#
# Well Explained in this video: https://www.youtube.com/watch?v=OAl6eAyP-yo
#
#

# In[32]:


from sklearn.metrics import roc_curve

y_pred_proba = knn.predict_proba(X_test)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)


# In[33]:


plt.plot([0, 1], [0, 1], "k--")
plt.plot(fpr, tpr, label="Knn")
plt.xlabel("fpr")
plt.ylabel("tpr")
plt.title("Knn(n_neighbors=11) ROC curve")
plt.show()


# In[34]:


# Area under ROC curve
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, y_pred_proba)


# # Hyper Parameter optimization
# Grid search is an approach to hyperparameter tuning that will methodically build and evaluate a model for each combination of algorithm parameters specified in a grid.
#
# Let’s consider the following example:
#
# Suppose, a machine learning model X takes hyperparameters a1, a2 and a3. In grid searching, you first define the range of values for each of the hyperparameters a1, a2 and a3. You can think of this as an array of values for each of the hyperparameters. Now the grid search technique will construct many versions of X with all the possible combinations of hyperparameter (a1, a2 and a3) values that you defined in the first place. This range of hyperparameter values is referred to as the grid.
#
# Suppose, you defined the grid as:
# a1 = [0,1,2,3,4,5]
# a2 = [10,20,30,40,5,60]
# a3 = [105,105,110,115,120,125]
#
# Note that, the array of values of that you are defining for the hyperparameters has to be legitimate in a sense that you cannot supply Floating type values to the array if the hyperparameter only takes Integer values.
#
# Now, grid search will begin its process of constructing several versions of X with the grid that you just defined.
#
# It will start with the combination of [0,10,105], and it will end with [5,60,125]. It will go through all the intermediate combinations between these two which makes grid search computationally very expensive.

# In[35]:


# import GridSearchCV
from sklearn.model_selection import GridSearchCV

# In case of classifier like knn the parameter to be tuned is n_neighbors
param_grid = {"n_neighbors": np.arange(1, 50)}
knn = KNeighborsClassifier()
knn_cv = GridSearchCV(knn, param_grid, cv=5)
knn_cv.fit(X, y)
print("Best Score:" + str(knn_cv.best_score_))
print("Best Parameters: " + str(knn_cv.best_params_))
lineapy.save(knn_cv, "nn for diabetes")


# In[36]:


# #### Don't forget to share and upvote if you found my notebook of use :)
