stub_data_assets = [
    {
        "file": "boston_house_prices.csv",
        "id": 6,
        "name": "Boston House Prices",
        "type": "dataset",
        "date": "1372944000",
        "code": {
            "text": 'print("Hello World")',
            "tokens": [
                {
                    "line": 1,
                    "start": 1,
                    "end": 6,
                    "intermediate": {
                        "file": "chart2.png",
                        "id": 10,
                        "name": "Value vs Year",
                        "type": "chart",
                        "date": "1272944000",
                    },
                },
            ],
        },
        "rest_endpoint": "https://acme.linea.ai/models?modelName=housing_model&data_point=[your_data]",
        "refresh_config": {
            "auto_refresh": True,
            "refresh_on_data_update": False,
            "refresh_on_frequency": True,
            "frequency": "Every Sunday",
            "notification": [],
        },
    },
    {
        "file": "chart1.png",
        "id": 7,
        "name": "Area vs Value",
        "type": "chart",
        "date": "1172944000",
        "code": {
            "text": "def generate_chart(data):\n\treturn data\nchart = generate_chart(data)",
            "tokens": [
                {
                    "line": 3,
                    "start": 1,
                    "end": 6,
                    "intermediate": {
                        "file": "chart2.png",
                        "id": 10,
                        "name": "Value vs Year",
                        "type": "chart",
                        "date": "1272944000",
                    },
                },
                {
                    "line": 1,
                    "start": 1,
                    "end": 4,
                    "intermediate": {
                        "file": "boston_house_prices.csv",
                        "id": 6,
                        "name": "Boston House Prices",
                        "type": "dataset",
                        "date": "1372944000",
                    },
                },
            ],
        },
        "rest_endpoint": "https://acme.linea.ai/models?modelName=housing_model&data_point=[your_data]",
        "refresh_config": {
            "auto_refresh": True,
            "refresh_on_data_update": False,
            "refresh_on_frequency": True,
            "frequency": "Every Sunday",
            "notification": [],
        },
    },
    {
        "file": "chart2.png",
        "id": 10,
        "name": "Value vs Year",
        "type": "chart",
        "date": "1272944000",
        "rest_endpoint": "https://acme.linea.ai/models?modelName=housing_model&data_point=[your_data]",
        "refresh_config": {
            "auto_refresh": True,
            "refresh_on_data_update": False,
            "refresh_on_frequency": True,
            "frequency": "Every Sunday",
            "notification": [],
        },
    },
    {
        "file": "beemovie.txt",
        "id": 19,
        "name": "Bee Movie",
        "type": "array",
        "date": "1072944000",
        "rest_endpoint": "https://acme.linea.ai/models?modelName=housing_model&data_point=[your_data]",
        "refresh_config": {
            "auto_refresh": True,
            "refresh_on_data_update": False,
            "refresh_on_frequency": True,
            "frequency": "Every Sunday",
            "notification": [],
        },
    },
    {
        "file": "birds.txt",
        "id": 20,
        "name": "Birds",
        "type": "array",
        "date": "1572944000",
        "rest_endpoint": "https://acme.linea.ai/models?modelName=housing_model&data_point=[your_data]",
        "refresh_config": {
            "auto_refresh": True,
            "refresh_on_data_update": False,
            "refresh_on_frequency": True,
            "frequency": "Every Sunday",
            "notification": [],
        },
    },
]
