import datetime
from pathlib import *
from lineapy.data.types import *
from lineapy.utils.utils import get_new_id

source_1 = SourceCode(
    code="""import lineapy
import cv2 as cv
import numpy as np
numpy.random.seed(0)
trainData = np.random.randint(0,100,(25,2)).astype(np.float32)
responses = np.random.randint(0,2,(25,1)).astype(np.float32)
red = trainData[responses.ravel()==0]
blue = trainData[responses.ravel()==1]
newcomer = np.random.randint(0,100,(1,2)).astype(np.float32)
lr = cv.ml.LogisticRegression_create()
lr.setTrainMethod(cv.ml.LogisticRegression_MINI_BATCH)
lr.setMiniBatchSize(1)
lr.setIterations(100)
lr.train(trainData, cv.ml.ROW_SAMPLE, responses)
ret, results = lr.predict(newcomer)

lineapy.save(results, \'results\')
""",
    location=PosixPath("[source file path]"),
)
import_1 = ImportNode(
    source_location=SourceLocation(
        lineno=1,
        col_offset=0,
        end_lineno=1,
        end_col_offset=14,
        source_code=source_1.id,
    ),
    name="lineapy",
    version="",
    package_name="lineapy",
)
import_2 = ImportNode(
    source_location=SourceLocation(
        lineno=2,
        col_offset=0,
        end_lineno=2,
        end_col_offset=16,
        source_code=source_1.id,
    ),
    name="cv2",
    version="",
    package_name="cv2",
)
call_2 = CallNode(
    source_location=SourceLocation(
        lineno=2,
        col_offset=0,
        end_lineno=2,
        end_col_offset=16,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_import",
    ).id,
    positional_args=[
        LiteralNode(
            value="cv2",
        ).id
    ],
)
call_3 = CallNode(
    source_location=SourceLocation(
        lineno=3,
        col_offset=0,
        end_lineno=3,
        end_col_offset=18,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_import",
    ).id,
    positional_args=[
        LiteralNode(
            value="numpy",
        ).id
    ],
)
import_3 = ImportNode(
    source_location=SourceLocation(
        lineno=3,
        col_offset=0,
        end_lineno=3,
        end_col_offset=18,
        source_code=source_1.id,
    ),
    name="numpy",
    version="",
    package_name="numpy",
)
call_6 = CallNode(
    source_location=SourceLocation(
        lineno=4,
        col_offset=0,
        end_lineno=4,
        end_col_offset=20,
        source_code=source_1.id,
    ),
    function_id=CallNode(
        source_location=SourceLocation(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=17,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="getattr",
        ).id,
        positional_args=[
            CallNode(
                source_location=SourceLocation(
                    lineno=4,
                    col_offset=0,
                    end_lineno=4,
                    end_col_offset=12,
                    source_code=source_1.id,
                ),
                function_id=LookupNode(
                    name="getattr",
                ).id,
                positional_args=[
                    call_3.id,
                    LiteralNode(
                        value="random",
                    ).id,
                ],
            ).id,
            LiteralNode(
                value="seed",
            ).id,
        ],
    ).id,
    positional_args=[
        LiteralNode(
            source_location=SourceLocation(
                lineno=4,
                col_offset=18,
                end_lineno=4,
                end_col_offset=19,
                source_code=source_1.id,
            ),
            value=0,
        ).id
    ],
)
call_13 = CallNode(
    source_location=SourceLocation(
        lineno=5,
        col_offset=12,
        end_lineno=5,
        end_col_offset=62,
        source_code=source_1.id,
    ),
    function_id=CallNode(
        source_location=SourceLocation(
            lineno=5,
            col_offset=12,
            end_lineno=5,
            end_col_offset=50,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="getattr",
        ).id,
        positional_args=[
            CallNode(
                source_location=SourceLocation(
                    lineno=5,
                    col_offset=12,
                    end_lineno=5,
                    end_col_offset=43,
                    source_code=source_1.id,
                ),
                function_id=CallNode(
                    source_location=SourceLocation(
                        lineno=5,
                        col_offset=12,
                        end_lineno=5,
                        end_col_offset=29,
                        source_code=source_1.id,
                    ),
                    function_id=LookupNode(
                        name="getattr",
                    ).id,
                    positional_args=[
                        CallNode(
                            source_location=SourceLocation(
                                lineno=5,
                                col_offset=12,
                                end_lineno=5,
                                end_col_offset=21,
                                source_code=source_1.id,
                            ),
                            function_id=LookupNode(
                                name="getattr",
                            ).id,
                            positional_args=[
                                call_3.id,
                                LiteralNode(
                                    value="random",
                                ).id,
                            ],
                        ).id,
                        LiteralNode(
                            value="randint",
                        ).id,
                    ],
                ).id,
                positional_args=[
                    LiteralNode(
                        source_location=SourceLocation(
                            lineno=5,
                            col_offset=30,
                            end_lineno=5,
                            end_col_offset=31,
                            source_code=source_1.id,
                        ),
                        value=0,
                    ).id,
                    LiteralNode(
                        source_location=SourceLocation(
                            lineno=5,
                            col_offset=32,
                            end_lineno=5,
                            end_col_offset=35,
                            source_code=source_1.id,
                        ),
                        value=100,
                    ).id,
                    CallNode(
                        source_location=SourceLocation(
                            lineno=5,
                            col_offset=36,
                            end_lineno=5,
                            end_col_offset=42,
                            source_code=source_1.id,
                        ),
                        function_id=LookupNode(
                            name="l_tuple",
                        ).id,
                        positional_args=[
                            LiteralNode(
                                source_location=SourceLocation(
                                    lineno=5,
                                    col_offset=37,
                                    end_lineno=5,
                                    end_col_offset=39,
                                    source_code=source_1.id,
                                ),
                                value=25,
                            ).id,
                            LiteralNode(
                                source_location=SourceLocation(
                                    lineno=5,
                                    col_offset=40,
                                    end_lineno=5,
                                    end_col_offset=41,
                                    source_code=source_1.id,
                                ),
                                value=2,
                            ).id,
                        ],
                    ).id,
                ],
            ).id,
            LiteralNode(
                value="astype",
            ).id,
        ],
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=5,
                col_offset=51,
                end_lineno=5,
                end_col_offset=61,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="getattr",
            ).id,
            positional_args=[
                call_3.id,
                LiteralNode(
                    value="float32",
                ).id,
            ],
        ).id
    ],
)
call_20 = CallNode(
    source_location=SourceLocation(
        lineno=6,
        col_offset=12,
        end_lineno=6,
        end_col_offset=60,
        source_code=source_1.id,
    ),
    function_id=CallNode(
        source_location=SourceLocation(
            lineno=6,
            col_offset=12,
            end_lineno=6,
            end_col_offset=48,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="getattr",
        ).id,
        positional_args=[
            CallNode(
                source_location=SourceLocation(
                    lineno=6,
                    col_offset=12,
                    end_lineno=6,
                    end_col_offset=41,
                    source_code=source_1.id,
                ),
                function_id=CallNode(
                    source_location=SourceLocation(
                        lineno=6,
                        col_offset=12,
                        end_lineno=6,
                        end_col_offset=29,
                        source_code=source_1.id,
                    ),
                    function_id=LookupNode(
                        name="getattr",
                    ).id,
                    positional_args=[
                        CallNode(
                            source_location=SourceLocation(
                                lineno=6,
                                col_offset=12,
                                end_lineno=6,
                                end_col_offset=21,
                                source_code=source_1.id,
                            ),
                            function_id=LookupNode(
                                name="getattr",
                            ).id,
                            positional_args=[
                                call_3.id,
                                LiteralNode(
                                    value="random",
                                ).id,
                            ],
                        ).id,
                        LiteralNode(
                            value="randint",
                        ).id,
                    ],
                ).id,
                positional_args=[
                    LiteralNode(
                        source_location=SourceLocation(
                            lineno=6,
                            col_offset=30,
                            end_lineno=6,
                            end_col_offset=31,
                            source_code=source_1.id,
                        ),
                        value=0,
                    ).id,
                    LiteralNode(
                        source_location=SourceLocation(
                            lineno=6,
                            col_offset=32,
                            end_lineno=6,
                            end_col_offset=33,
                            source_code=source_1.id,
                        ),
                        value=2,
                    ).id,
                    CallNode(
                        source_location=SourceLocation(
                            lineno=6,
                            col_offset=34,
                            end_lineno=6,
                            end_col_offset=40,
                            source_code=source_1.id,
                        ),
                        function_id=LookupNode(
                            name="l_tuple",
                        ).id,
                        positional_args=[
                            LiteralNode(
                                source_location=SourceLocation(
                                    lineno=6,
                                    col_offset=35,
                                    end_lineno=6,
                                    end_col_offset=37,
                                    source_code=source_1.id,
                                ),
                                value=25,
                            ).id,
                            LiteralNode(
                                source_location=SourceLocation(
                                    lineno=6,
                                    col_offset=38,
                                    end_lineno=6,
                                    end_col_offset=39,
                                    source_code=source_1.id,
                                ),
                                value=1,
                            ).id,
                        ],
                    ).id,
                ],
            ).id,
            LiteralNode(
                value="astype",
            ).id,
        ],
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=6,
                col_offset=49,
                end_lineno=6,
                end_col_offset=59,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="getattr",
            ).id,
            positional_args=[
                call_3.id,
                LiteralNode(
                    value="float32",
                ).id,
            ],
        ).id
    ],
)
call_24 = CallNode(
    source_location=SourceLocation(
        lineno=7,
        col_offset=6,
        end_lineno=7,
        end_col_offset=37,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="getitem",
    ).id,
    positional_args=[
        call_13.id,
        CallNode(
            source_location=SourceLocation(
                lineno=7,
                col_offset=16,
                end_lineno=7,
                end_col_offset=36,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="eq",
            ).id,
            positional_args=[
                CallNode(
                    source_location=SourceLocation(
                        lineno=7,
                        col_offset=16,
                        end_lineno=7,
                        end_col_offset=33,
                        source_code=source_1.id,
                    ),
                    function_id=CallNode(
                        source_location=SourceLocation(
                            lineno=7,
                            col_offset=16,
                            end_lineno=7,
                            end_col_offset=31,
                            source_code=source_1.id,
                        ),
                        function_id=LookupNode(
                            name="getattr",
                        ).id,
                        positional_args=[
                            call_20.id,
                            LiteralNode(
                                value="ravel",
                            ).id,
                        ],
                    ).id,
                ).id,
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=7,
                        col_offset=35,
                        end_lineno=7,
                        end_col_offset=36,
                        source_code=source_1.id,
                    ),
                    value=0,
                ).id,
            ],
        ).id,
    ],
)
call_28 = CallNode(
    source_location=SourceLocation(
        lineno=8,
        col_offset=7,
        end_lineno=8,
        end_col_offset=38,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="getitem",
    ).id,
    positional_args=[
        call_13.id,
        CallNode(
            source_location=SourceLocation(
                lineno=8,
                col_offset=17,
                end_lineno=8,
                end_col_offset=37,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="eq",
            ).id,
            positional_args=[
                CallNode(
                    source_location=SourceLocation(
                        lineno=8,
                        col_offset=17,
                        end_lineno=8,
                        end_col_offset=34,
                        source_code=source_1.id,
                    ),
                    function_id=CallNode(
                        source_location=SourceLocation(
                            lineno=8,
                            col_offset=17,
                            end_lineno=8,
                            end_col_offset=32,
                            source_code=source_1.id,
                        ),
                        function_id=LookupNode(
                            name="getattr",
                        ).id,
                        positional_args=[
                            call_20.id,
                            LiteralNode(
                                value="ravel",
                            ).id,
                        ],
                    ).id,
                ).id,
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=8,
                        col_offset=36,
                        end_lineno=8,
                        end_col_offset=37,
                        source_code=source_1.id,
                    ),
                    value=1,
                ).id,
            ],
        ).id,
    ],
)
call_38 = CallNode(
    source_location=SourceLocation(
        lineno=10,
        col_offset=5,
        end_lineno=10,
        end_col_offset=38,
        source_code=source_1.id,
    ),
    function_id=CallNode(
        source_location=SourceLocation(
            lineno=10,
            col_offset=5,
            end_lineno=10,
            end_col_offset=36,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="getattr",
        ).id,
        positional_args=[
            CallNode(
                source_location=SourceLocation(
                    lineno=10,
                    col_offset=5,
                    end_lineno=10,
                    end_col_offset=10,
                    source_code=source_1.id,
                ),
                function_id=LookupNode(
                    name="getattr",
                ).id,
                positional_args=[
                    call_2.id,
                    LiteralNode(
                        value="ml",
                    ).id,
                ],
            ).id,
            LiteralNode(
                value="LogisticRegression_create",
            ).id,
        ],
    ).id,
)
call_42 = CallNode(
    source_location=SourceLocation(
        lineno=11,
        col_offset=0,
        end_lineno=11,
        end_col_offset=54,
        source_code=source_1.id,
    ),
    function_id=CallNode(
        source_location=SourceLocation(
            lineno=11,
            col_offset=0,
            end_lineno=11,
            end_col_offset=17,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="getattr",
        ).id,
        positional_args=[
            call_38.id,
            LiteralNode(
                value="setTrainMethod",
            ).id,
        ],
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=11,
                col_offset=18,
                end_lineno=11,
                end_col_offset=53,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="getattr",
            ).id,
            positional_args=[
                CallNode(
                    source_location=SourceLocation(
                        lineno=11,
                        col_offset=18,
                        end_lineno=11,
                        end_col_offset=23,
                        source_code=source_1.id,
                    ),
                    function_id=LookupNode(
                        name="getattr",
                    ).id,
                    positional_args=[
                        call_2.id,
                        LiteralNode(
                            value="ml",
                        ).id,
                    ],
                ).id,
                LiteralNode(
                    value="LogisticRegression_MINI_BATCH",
                ).id,
            ],
        ).id
    ],
)
call_44 = CallNode(
    source_location=SourceLocation(
        lineno=12,
        col_offset=0,
        end_lineno=12,
        end_col_offset=22,
        source_code=source_1.id,
    ),
    function_id=CallNode(
        source_location=SourceLocation(
            lineno=12,
            col_offset=0,
            end_lineno=12,
            end_col_offset=19,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="getattr",
        ).id,
        positional_args=[
            call_38.id,
            LiteralNode(
                value="setMiniBatchSize",
            ).id,
        ],
    ).id,
    positional_args=[
        LiteralNode(
            source_location=SourceLocation(
                lineno=12,
                col_offset=20,
                end_lineno=12,
                end_col_offset=21,
                source_code=source_1.id,
            ),
            value=1,
        ).id
    ],
)
call_46 = CallNode(
    source_location=SourceLocation(
        lineno=13,
        col_offset=0,
        end_lineno=13,
        end_col_offset=21,
        source_code=source_1.id,
    ),
    function_id=CallNode(
        source_location=SourceLocation(
            lineno=13,
            col_offset=0,
            end_lineno=13,
            end_col_offset=16,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="getattr",
        ).id,
        positional_args=[
            call_38.id,
            LiteralNode(
                value="setIterations",
            ).id,
        ],
    ).id,
    positional_args=[
        LiteralNode(
            source_location=SourceLocation(
                lineno=13,
                col_offset=17,
                end_lineno=13,
                end_col_offset=20,
                source_code=source_1.id,
            ),
            value=100,
        ).id
    ],
)
call_53 = CallNode(
    source_location=SourceLocation(
        lineno=15,
        col_offset=0,
        end_lineno=15,
        end_col_offset=35,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_unpack_sequence",
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=15,
                col_offset=15,
                end_lineno=15,
                end_col_offset=35,
                source_code=source_1.id,
            ),
            function_id=CallNode(
                source_location=SourceLocation(
                    lineno=15,
                    col_offset=15,
                    end_lineno=15,
                    end_col_offset=25,
                    source_code=source_1.id,
                ),
                function_id=LookupNode(
                    name="getattr",
                ).id,
                positional_args=[
                    MutateNode(
                        source_id=call_38.id,
                        call_id=CallNode(
                            source_location=SourceLocation(
                                lineno=14,
                                col_offset=0,
                                end_lineno=14,
                                end_col_offset=48,
                                source_code=source_1.id,
                            ),
                            function_id=CallNode(
                                source_location=SourceLocation(
                                    lineno=14,
                                    col_offset=0,
                                    end_lineno=14,
                                    end_col_offset=8,
                                    source_code=source_1.id,
                                ),
                                function_id=LookupNode(
                                    name="getattr",
                                ).id,
                                positional_args=[
                                    call_38.id,
                                    LiteralNode(
                                        value="train",
                                    ).id,
                                ],
                            ).id,
                            positional_args=[
                                call_13.id,
                                CallNode(
                                    source_location=SourceLocation(
                                        lineno=14,
                                        col_offset=20,
                                        end_lineno=14,
                                        end_col_offset=36,
                                        source_code=source_1.id,
                                    ),
                                    function_id=LookupNode(
                                        name="getattr",
                                    ).id,
                                    positional_args=[
                                        CallNode(
                                            source_location=SourceLocation(
                                                lineno=14,
                                                col_offset=20,
                                                end_lineno=14,
                                                end_col_offset=25,
                                                source_code=source_1.id,
                                            ),
                                            function_id=LookupNode(
                                                name="getattr",
                                            ).id,
                                            positional_args=[
                                                call_2.id,
                                                LiteralNode(
                                                    value="ml",
                                                ).id,
                                            ],
                                        ).id,
                                        LiteralNode(
                                            value="ROW_SAMPLE",
                                        ).id,
                                    ],
                                ).id,
                                call_20.id,
                            ],
                        ).id,
                    ).id,
                    LiteralNode(
                        value="predict",
                    ).id,
                ],
            ).id,
            positional_args=[
                CallNode(
                    source_location=SourceLocation(
                        lineno=9,
                        col_offset=11,
                        end_lineno=9,
                        end_col_offset=60,
                        source_code=source_1.id,
                    ),
                    function_id=CallNode(
                        source_location=SourceLocation(
                            lineno=9,
                            col_offset=11,
                            end_lineno=9,
                            end_col_offset=48,
                            source_code=source_1.id,
                        ),
                        function_id=LookupNode(
                            name="getattr",
                        ).id,
                        positional_args=[
                            CallNode(
                                source_location=SourceLocation(
                                    lineno=9,
                                    col_offset=11,
                                    end_lineno=9,
                                    end_col_offset=41,
                                    source_code=source_1.id,
                                ),
                                function_id=CallNode(
                                    source_location=SourceLocation(
                                        lineno=9,
                                        col_offset=11,
                                        end_lineno=9,
                                        end_col_offset=28,
                                        source_code=source_1.id,
                                    ),
                                    function_id=LookupNode(
                                        name="getattr",
                                    ).id,
                                    positional_args=[
                                        CallNode(
                                            source_location=SourceLocation(
                                                lineno=9,
                                                col_offset=11,
                                                end_lineno=9,
                                                end_col_offset=20,
                                                source_code=source_1.id,
                                            ),
                                            function_id=LookupNode(
                                                name="getattr",
                                            ).id,
                                            positional_args=[
                                                call_3.id,
                                                LiteralNode(
                                                    value="random",
                                                ).id,
                                            ],
                                        ).id,
                                        LiteralNode(
                                            value="randint",
                                        ).id,
                                    ],
                                ).id,
                                positional_args=[
                                    LiteralNode(
                                        source_location=SourceLocation(
                                            lineno=9,
                                            col_offset=29,
                                            end_lineno=9,
                                            end_col_offset=30,
                                            source_code=source_1.id,
                                        ),
                                        value=0,
                                    ).id,
                                    LiteralNode(
                                        source_location=SourceLocation(
                                            lineno=9,
                                            col_offset=31,
                                            end_lineno=9,
                                            end_col_offset=34,
                                            source_code=source_1.id,
                                        ),
                                        value=100,
                                    ).id,
                                    CallNode(
                                        source_location=SourceLocation(
                                            lineno=9,
                                            col_offset=35,
                                            end_lineno=9,
                                            end_col_offset=40,
                                            source_code=source_1.id,
                                        ),
                                        function_id=LookupNode(
                                            name="l_tuple",
                                        ).id,
                                        positional_args=[
                                            LiteralNode(
                                                source_location=SourceLocation(
                                                    lineno=9,
                                                    col_offset=36,
                                                    end_lineno=9,
                                                    end_col_offset=37,
                                                    source_code=source_1.id,
                                                ),
                                                value=1,
                                            ).id,
                                            LiteralNode(
                                                source_location=SourceLocation(
                                                    lineno=9,
                                                    col_offset=38,
                                                    end_lineno=9,
                                                    end_col_offset=39,
                                                    source_code=source_1.id,
                                                ),
                                                value=2,
                                            ).id,
                                        ],
                                    ).id,
                                ],
                            ).id,
                            LiteralNode(
                                value="astype",
                            ).id,
                        ],
                    ).id,
                    positional_args=[
                        CallNode(
                            source_location=SourceLocation(
                                lineno=9,
                                col_offset=49,
                                end_lineno=9,
                                end_col_offset=59,
                                source_code=source_1.id,
                            ),
                            function_id=LookupNode(
                                name="getattr",
                            ).id,
                            positional_args=[
                                call_3.id,
                                LiteralNode(
                                    value="float32",
                                ).id,
                            ],
                        ).id
                    ],
                ).id
            ],
        ).id,
        LiteralNode(
            value=2,
        ).id,
    ],
)
call_54 = CallNode(
    source_location=SourceLocation(
        lineno=15,
        col_offset=0,
        end_lineno=15,
        end_col_offset=35,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="getitem",
    ).id,
    positional_args=[
        call_53.id,
        LiteralNode(
            value=0,
        ).id,
    ],
)
call_57 = CallNode(
    source_location=SourceLocation(
        lineno=17,
        col_offset=0,
        end_lineno=17,
        end_col_offset=32,
        source_code=source_1.id,
    ),
    function_id=CallNode(
        source_location=SourceLocation(
            lineno=17,
            col_offset=0,
            end_lineno=17,
            end_col_offset=12,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="getattr",
        ).id,
        positional_args=[
            CallNode(
                source_location=SourceLocation(
                    lineno=1,
                    col_offset=0,
                    end_lineno=1,
                    end_col_offset=14,
                    source_code=source_1.id,
                ),
                function_id=LookupNode(
                    name="l_import",
                ).id,
                positional_args=[
                    LiteralNode(
                        value="lineapy",
                    ).id
                ],
            ).id,
            LiteralNode(
                value="save",
            ).id,
        ],
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=15,
                col_offset=0,
                end_lineno=15,
                end_col_offset=35,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="getitem",
            ).id,
            positional_args=[
                call_53.id,
                LiteralNode(
                    value=1,
                ).id,
            ],
        ).id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=17,
                col_offset=22,
                end_lineno=17,
                end_col_offset=31,
                source_code=source_1.id,
            ),
            value="results",
        ).id,
    ],
)
