import datetime
from pathlib import *
from lineapy.data.types import *
from lineapy.utils.utils import get_new_id

source_1 = SourceCode(
    code="""print(True and False)
print(True or False)
x = True and False
""",
    location=PosixPath("[source file path]"),
)
call_2 = CallNode(
    source_location=SourceLocation(
        lineno=1,
        col_offset=0,
        end_lineno=1,
        end_col_offset=21,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        source_location=SourceLocation(
            lineno=1,
            col_offset=0,
            end_lineno=1,
            end_col_offset=5,
            source_code=source_1.id,
        ),
        name="print",
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=1,
                col_offset=6,
                end_lineno=1,
                end_col_offset=20,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="and_",
            ).id,
            positional_args=[
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=1,
                        col_offset=6,
                        end_lineno=1,
                        end_col_offset=10,
                        source_code=source_1.id,
                    ),
                    value=True,
                ).id,
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=1,
                        col_offset=15,
                        end_lineno=1,
                        end_col_offset=20,
                        source_code=source_1.id,
                    ),
                    value=False,
                ).id,
            ],
        ).id
    ],
)
call_4 = CallNode(
    source_location=SourceLocation(
        lineno=2,
        col_offset=0,
        end_lineno=2,
        end_col_offset=20,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        source_location=SourceLocation(
            lineno=2,
            col_offset=0,
            end_lineno=2,
            end_col_offset=5,
            source_code=source_1.id,
        ),
        name="print",
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=2,
                col_offset=6,
                end_lineno=2,
                end_col_offset=19,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="or_",
            ).id,
            positional_args=[
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=2,
                        col_offset=6,
                        end_lineno=2,
                        end_col_offset=10,
                        source_code=source_1.id,
                    ),
                    value=True,
                ).id,
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=2,
                        col_offset=14,
                        end_lineno=2,
                        end_col_offset=19,
                        source_code=source_1.id,
                    ),
                    value=False,
                ).id,
            ],
        ).id
    ],
)
call_5 = CallNode(
    source_location=SourceLocation(
        lineno=3,
        col_offset=4,
        end_lineno=3,
        end_col_offset=18,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="and_",
    ).id,
    positional_args=[
        LiteralNode(
            source_location=SourceLocation(
                lineno=3,
                col_offset=4,
                end_lineno=3,
                end_col_offset=8,
                source_code=source_1.id,
            ),
            value=True,
        ).id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=3,
                col_offset=13,
                end_lineno=3,
                end_col_offset=18,
                source_code=source_1.id,
            ),
            value=False,
        ).id,
    ],
)
