import datetime
from pathlib import *
from lineapy.data.types import *
from lineapy.utils.utils import get_new_id

source_1 = SourceCode(
    code="""
import lineapy
x = (y := 10)
(z := x) < 10
(x := 7) > 9
(a := z)
(z := x) > 9
lineapy.save(z, \'z\')
""",
    location=PosixPath("[source file path]"),
)
import_1 = ImportNode(
    source_location=SourceLocation(
        lineno=2,
        col_offset=0,
        end_lineno=2,
        end_col_offset=14,
        source_code=source_1.id,
    ),
    name="lineapy",
    version="",
    package_name="lineapy",
)
call_3 = CallNode(
    source_location=SourceLocation(
        lineno=4,
        col_offset=1,
        end_lineno=4,
        end_col_offset=7,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_alias",
    ).id,
    positional_args=[
        CallNode(
            source_location=SourceLocation(
                lineno=3,
                col_offset=5,
                end_lineno=3,
                end_col_offset=12,
                source_code=source_1.id,
            ),
            function_id=LookupNode(
                name="l_alias",
            ).id,
            positional_args=[
                LiteralNode(
                    source_location=SourceLocation(
                        lineno=3,
                        col_offset=10,
                        end_lineno=3,
                        end_col_offset=12,
                        source_code=source_1.id,
                    ),
                    value=10,
                ).id
            ],
        ).id
    ],
)
call_4 = CallNode(
    source_location=SourceLocation(
        lineno=4,
        col_offset=0,
        end_lineno=4,
        end_col_offset=13,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="lt",
    ).id,
    positional_args=[
        call_3.id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=4,
                col_offset=11,
                end_lineno=4,
                end_col_offset=13,
                source_code=source_1.id,
            ),
            value=10,
        ).id,
    ],
)
call_5 = CallNode(
    source_location=SourceLocation(
        lineno=5,
        col_offset=1,
        end_lineno=5,
        end_col_offset=7,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_alias",
    ).id,
    positional_args=[
        LiteralNode(
            source_location=SourceLocation(
                lineno=5,
                col_offset=6,
                end_lineno=5,
                end_col_offset=7,
                source_code=source_1.id,
            ),
            value=7,
        ).id
    ],
)
call_6 = CallNode(
    source_location=SourceLocation(
        lineno=5,
        col_offset=0,
        end_lineno=5,
        end_col_offset=12,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="gt",
    ).id,
    positional_args=[
        call_5.id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=5,
                col_offset=11,
                end_lineno=5,
                end_col_offset=12,
                source_code=source_1.id,
            ),
            value=9,
        ).id,
    ],
)
call_7 = CallNode(
    source_location=SourceLocation(
        lineno=6,
        col_offset=1,
        end_lineno=6,
        end_col_offset=7,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_alias",
    ).id,
    positional_args=[call_3.id],
)
call_8 = CallNode(
    source_location=SourceLocation(
        lineno=7,
        col_offset=1,
        end_lineno=7,
        end_col_offset=7,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="l_alias",
    ).id,
    positional_args=[call_5.id],
)
call_9 = CallNode(
    source_location=SourceLocation(
        lineno=7,
        col_offset=0,
        end_lineno=7,
        end_col_offset=12,
        source_code=source_1.id,
    ),
    function_id=LookupNode(
        name="gt",
    ).id,
    positional_args=[
        call_8.id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=7,
                col_offset=11,
                end_lineno=7,
                end_col_offset=12,
                source_code=source_1.id,
            ),
            value=9,
        ).id,
    ],
)
call_11 = CallNode(
    source_location=SourceLocation(
        lineno=8,
        col_offset=0,
        end_lineno=8,
        end_col_offset=20,
        source_code=source_1.id,
    ),
    function_id=CallNode(
        source_location=SourceLocation(
            lineno=8,
            col_offset=0,
            end_lineno=8,
            end_col_offset=12,
            source_code=source_1.id,
        ),
        function_id=LookupNode(
            name="getattr",
        ).id,
        positional_args=[
            CallNode(
                source_location=SourceLocation(
                    lineno=2,
                    col_offset=0,
                    end_lineno=2,
                    end_col_offset=14,
                    source_code=source_1.id,
                ),
                function_id=LookupNode(
                    name="l_import",
                ).id,
                positional_args=[
                    LiteralNode(
                        value="lineapy",
                    ).id
                ],
            ).id,
            LiteralNode(
                value="save",
            ).id,
        ],
    ).id,
    positional_args=[
        call_8.id,
        LiteralNode(
            source_location=SourceLocation(
                lineno=8,
                col_offset=16,
                end_lineno=8,
                end_col_offset=19,
                source_code=source_1.id,
            ),
            value="z",
        ).id,
    ],
)
