"""pipeline_inputs

Revision ID: 656685b05590
Revises: 07d0db31e15f
Create Date: 2022-11-15 20:50:08.371972

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "656685b05590"
down_revision = "07d0db31e15f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assigned_variable_node",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("variable_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", "variable_name"),
    )
    op.create_table(
        "execution",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("isUDF", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_code",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("jupyter_execution_count", sa.Integer(), nullable=True),
        sa.Column("jupyter_session_id", sa.String(), nullable=True),
        sa.CheckConstraint(
            "(jupyter_execution_count IS NULL) = (jupyter_session_id is NULL)"
        ),
        sa.CheckConstraint(
            "(path IS NOT NULL) != ((jupyter_execution_count IS NOT NULL) AND (jupyter_execution_count IS NOT NULL))"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inputvar_to_pipeline",
        sa.Column("pipeline_id", sa.Integer(), nullable=True),
        sa.Column("var_node_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipeline.id"],
        ),
        sa.ForeignKeyConstraint(
            ["var_node_id"],
            ["assigned_variable_node.id"],
        ),
    )
    op.create_table(
        "node",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column(
            "node_type",
            sa.Enum(
                "Node",
                "CallNode",
                "LiteralNode",
                "ImportNode",
                "LookupNode",
                "MutateNode",
                "GlobalNode",
                "IfNode",
                "ElseNode",
                name="nodetype",
            ),
            nullable=True,
        ),
        sa.Column("lineno", sa.Integer(), nullable=True),
        sa.Column("col_offset", sa.Integer(), nullable=True),
        sa.Column("end_lineno", sa.Integer(), nullable=True),
        sa.Column("end_col_offset", sa.Integer(), nullable=True),
        sa.Column("control_dependency", sa.String(), nullable=True),
        sa.Column("source_code_id", sa.String(), nullable=True),
        sa.CheckConstraint(
            "(lineno IS NULL) = (col_offset is NULL) and (col_offset is NULL) = (end_lineno is NULL) and (end_lineno is NULL) = (end_col_offset is NULL) and (end_col_offset is NULL) = (source_code_id is NULL)"
        ),
        sa.ForeignKeyConstraint(
            ["control_dependency"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_code_id"],
            ["source_code.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_context",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "environment_type",
            sa.Enum("JUPYTER", "SCRIPT", name="sessiontype"),
            nullable=True,
        ),
        sa.Column("python_version", sa.String(), nullable=True),
        sa.Column("creation_time", sa.DateTime(), nullable=True),
        sa.Column("working_directory", sa.String(), nullable=True),
        sa.Column("session_name", sa.String(), nullable=True),
        sa.Column("user_name", sa.String(), nullable=True),
        sa.Column("hardware_spec", sa.String(), nullable=True),
        sa.Column("execution_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "var_to_pipeline",
        sa.Column("pipeline_id", sa.Integer(), nullable=True),
        sa.Column("var_node_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipeline.id"],
        ),
        sa.ForeignKeyConstraint(
            ["var_node_id"],
            ["assigned_variable_node.id"],
        ),
    )
    op.create_table(
        "artifact",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("execution_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name",
            "node_id",
            "execution_id",
            "version",
            name="_unique_artifact_name_for_a_node_id_and_exec_id",
        ),
        sa.UniqueConstraint(
            "name", "version", name="_unique_artifact_name_and_version"
        ),
    )
    op.create_table(
        "call_node",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("function_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "global_node",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("call_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "import_node",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("package_name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "literal_assign_node",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "value_type",
            sa.Enum(
                "String",
                "Integer",
                "Float",
                "Boolean",
                "NoneType",
                "Ellipsis",
                "Bytes",
                name="literaltype",
            ),
            nullable=True,
        ),
        sa.Column("value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lookup",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mutate_node",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("call_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "node_value",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("execution_id", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column(
            "value_type",
            sa.Enum(
                "chart", "array", "dataset", "code", "value", name="valuetype"
            ),
            nullable=True,
        ),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("node_id", "execution_id"),
    )
    op.create_table(
        "artifact_to_pipeline",
        sa.Column("pipeline_id", sa.Integer(), nullable=True),
        sa.Column("artifact_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipeline.id"],
        ),
    )
    op.create_table(
        "dependency",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pipeline_id", sa.Integer(), nullable=False),
        sa.Column("post_artifact_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipeline.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_artifact_id"],
            ["artifact.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "else_node",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("companion_id", sa.String(), nullable=True),
        sa.Column("unexec_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["companion_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unexec_id"],
            ["literal_assign_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "global_reference",
        sa.Column("call_node_id", sa.String(), nullable=False),
        sa.Column("variable_node_id", sa.String(), nullable=False),
        sa.Column("variable_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_node_id"],
            ["call_node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variable_node_id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint(
            "call_node_id", "variable_node_id", "variable_name"
        ),
    )
    op.create_table(
        "if_node",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("test_id", sa.String(), nullable=True),
        sa.Column("companion_id", sa.String(), nullable=True),
        sa.Column("unexec_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["companion_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unexec_id"],
            ["literal_assign_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "implicit_dependency",
        sa.Column("call_node_id", sa.String(), nullable=False),
        sa.Column("arg_node_id", sa.String(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["arg_node_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["call_node_id"],
            ["call_node.id"],
        ),
        sa.PrimaryKeyConstraint("call_node_id", "arg_node_id", "index"),
    )
    op.create_table(
        "keyword_arg",
        sa.Column("call_node_id", sa.String(), nullable=False),
        sa.Column("arg_node_id", sa.String(), nullable=False),
        sa.Column("starred", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["arg_node_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["call_node_id"],
            ["call_node.id"],
        ),
        sa.PrimaryKeyConstraint("call_node_id", "arg_node_id", "name"),
    )
    op.create_table(
        "mlflow_artifact_storage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("artifact_id", sa.Integer(), nullable=False),
        sa.Column("backend", sa.String(), nullable=False),
        sa.Column("tracking_uri", sa.String(), nullable=False),
        sa.Column("registry_uri", sa.String(), nullable=True),
        sa.Column("model_uri", sa.String(), nullable=False),
        sa.Column("model_flavor", sa.String(), nullable=False),
        sa.Column("delete_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifact.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "positional_arg",
        sa.Column("call_node_id", sa.String(), nullable=False),
        sa.Column("arg_node_id", sa.String(), nullable=False),
        sa.Column("starred", sa.Boolean(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["arg_node_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["call_node_id"],
            ["call_node.id"],
        ),
        sa.PrimaryKeyConstraint("call_node_id", "arg_node_id", "index"),
    )
    op.create_table(
        "reuse_artifact_to_pipeline",
        sa.Column("pipeline_id", sa.Integer(), nullable=True),
        sa.Column("artifact_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipeline.id"],
        ),
    )
    op.create_table(
        "dependency_to_artifact_table",
        sa.Column("dependency_id", sa.Integer(), nullable=True),
        sa.Column("artifact_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dependency_id"],
            ["dependency.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dependency_to_artifact_table")
    op.drop_table("reuse_artifact_to_pipeline")
    op.drop_table("positional_arg")
    op.drop_table("mlflow_artifact_storage")
    op.drop_table("keyword_arg")
    op.drop_table("implicit_dependency")
    op.drop_table("if_node")
    op.drop_table("global_reference")
    op.drop_table("else_node")
    op.drop_table("dependency")
    op.drop_table("artifact_to_pipeline")
    op.drop_table("node_value")
    op.drop_table("mutate_node")
    op.drop_table("lookup")
    op.drop_table("literal_assign_node")
    op.drop_table("import_node")
    op.drop_table("global_node")
    op.drop_table("call_node")
    op.drop_table("artifact")
    op.drop_table("var_to_pipeline")
    op.drop_table("session_context")
    op.drop_table("node")
    op.drop_table("inputvar_to_pipeline")
    op.drop_table("source_code")
    op.drop_table("pipeline")
    op.drop_table("execution")
    op.drop_table("assigned_variable_node")
    # ### end Alembic commands ###
