"""add-mlflow-metadata

Revision ID: dfda133f6ada
Revises: 4907800d9126
Create Date: 2022-10-23 23:34:41.896866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfda133f6ada'
down_revision = '4907800d9126'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
