# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python

on:
  pull_request:
    paths:
      - "**.py"
      - "**.ipynb"
  
concurrency:
  group: "${{ github.head_ref }}"
  cancel-in-progress: true
jobs:
  test:
    name: Tests
    uses: LineaLabs/lineapy/.github/workflows/test.yml@main
  format:
    name: Format code
    uses: LineaLabs/lineapy/.github/workflows/format.yml@main
  lint:
    name: Lint
    uses: LineaLabs/lineapy/.github/workflows/lint.yml@main
  typechecks:
    name: Typechecks
    uses: LineaLabs/lineapy/.github/workflows/typecheck.yml@main