# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ray

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "lineapy/plugins/jinja_templates/ray/*"
      - "lineapy/plugins/jinja_templates/task/*"
      - "lineapy/plugins/jinja_templates/module/*"
      - "lineapy/plugins/ray_pipeline_writer.py"
      - "lineapy/plugins/base_pipeline_writer.py"
      - "tests/unit/plugins/framework_specific/ray/*"
      - "test_pipeline_ray_req.txt"
  pull_request:
    paths:
      - "lineapy/plugins/jinja_templates/ray/*"
      - "lineapy/plugins/jinja_templates/task/*"
      - "lineapy/plugins/jinja_templates/module/*"
      - "lineapy/plugins/ray_pipeline_writer.py"
      - "lineapy/plugins/base_pipeline_writer.py"
      - "tests/unit/plugins/framework_specific/ray/*"
      - "test_pipeline_ray_req.txt"
jobs:
  ray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: "recursive"
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt && python setup.py install && rm -rf build
      - name: Test with pytest
        run: |
          pytest -vv -m 'ray'
